import type { StyleGroup } from "@/types/styleTypes";
import { globalCssOptions } from "../options";

export const ColorGroup: StyleGroup = {
  groupName: "Color",
  propertyNames: ["accent-color", "caret-color", "color", "color-scheme"],
  groups: [
    {
      name: "accent-color",
      nameForTitle: "Accent Color",
      type: "string",
      description:
        "Sets the accent color for user interface controls generated by the element, such as form control elements and progress bars.",
      value: "",
      options: ["auto", "color", ...globalCssOptions],
    },
    {
      name: "caret-color",
      nameForTitle: "Caret Color",
      type: "color",
      description: "Sets the color of the text input cursor (caret).",
      value: "",
      options: ["auto", "color", ...globalCssOptions],
    },
    {
      name: "color",
      nameForTitle: "Color",
      type: "string",
      description: "Defines the color of the text for the element.",
      value: "",
      options: ["color", ...globalCssOptions],
    },
    {
      name: "color-scheme",
      nameForTitle: "Color Scheme",
      type: "string",
      description:
        "Specifies the preferred color scheme for the element, allowing for light and dark modes.",
      value: "",
      options: ["normal", "light", "dark", "light dark", "only light", ...globalCssOptions],
    },
  ],
};
