import { Style, StyleGroup } from "@/types/styleTypes";
export const globalCssOptions = ["inherit", "initial", "revert", "revert-layer", "unset"];
export const customAndGlobalCssOptions = [
  "custom",
  "inherit",
  "initial",
  "revert",
  "revert-layer",
  "unset",
];
export const namedPositions = ["left", "right", "top", "bottom", "center"];
export const lengthUnits = [
  "px",
  "%",
  "em",
  "fr",
  "rem",
  "cm",
  "mm",
  "in",
  "pt",
  "pc",
  "ch",
  "vw",
  "vh",
  "vmin",
  "vmax",
];
export const LengthUnit: Style = {
  name: "length",
  nameForTitle: "Length",
  type: "string",
  description: "Unit of lengths",
  value: "",
  options: [...lengthUnits],
};
export const GLOBAL_STYLES: Style[] = [
  {
    name: "align-content",
    nameForTitle: "Alignment",
    value: "",
  },
  {
    name: "all",
    nameForTitle: "All",
    value: "",
  },
  {
    name: "backface-visibility",
    nameForTitle: "Backface Visibility",
    value: "",
  },
  {
    name: "background-color",
    nameForTitle: "Background",
    value: "",
  },
  {
    name: "block-size",
    nameForTitle: "Block-Size",
    value: "",
  },
  {
    name: "box-sizing",
    nameForTitle: "Box",
    value: "",
  },
  {
    name: "break-after",
    nameForTitle: "Break",
    value: "",
  },
  {
    name: "color",
    nameForTitle: "Color",
    value: "",
  },
  {
    name: "column-count",
    nameForTitle: "Column and Row",
    value: "",
  },
  {
    name: "contain",
    nameForTitle: "Contain",
    value: "",
  },
  {
    name: "content",
    nameForTitle: "Content",
    value: "",
  },
  {
    name: "cursor",
    nameForTitle: "Cursor",
    value: "",
  },
  {
    name: "display",
    nameForTitle: "Display",
    value: "",
  },
  {
    name: "flex-basis",
    nameForTitle: "Flex",
    value: "",
  },
  {
    name: "float",
    nameForTitle: "Float",
    value: "",
  },
  {
    name: "height",
    nameForTitle: "Height",
    value: "",
  },
  {
    name: "inline-size",
    nameForTitle: "Inline-Size",
    value: "",
  },
  {
    name: "justify-content",
    nameForTitle: "Justify",
    value: "",
  },
  {
    name: "line-break",
    nameForTitle: "Line",
    value: "",
  },
  {
    name: "list-style-image",
    nameForTitle: "List",
    value: "",
  },
  {
    name: "margin-top",
    nameForTitle: "Margin",
    value: "",
  },
  {
    name: "outline-color",
    nameForTitle: "Outline",
    value: "",
  },
  {
    name: "overflow-anchor",
    nameForTitle: "Overflow",
    value: "",
  },
  {
    name: "overscroll-behavior-x",
    nameForTitle: "Overscroll",
    value: "",
  },
  {
    name: "padding-top",
    nameForTitle: "Padding",
    value: "",
  },
  {
    name: "place-content",
    nameForTitle: "Place",
    value: "",
  },
  {
    name: "position",
    nameForTitle: "Position",
    value: "",
  },
  {
    name: "scrollbar-color",
    nameForTitle: "Scrollbar",
    value: "",
  },
  {
    name: "empty-cells",
    nameForTitle: "Table",
    value: "",
  },
  {
    name: "text-align",
    nameForTitle: "Text",
    value: "",
  },
  {
    name: "white-space",
    nameForTitle: "White-Space",
    value: "",
  },
  {
    name: "width",
    nameForTitle: "Width",
    value: "",
  },
  {
    name: "word-break",
    nameForTitle: "Word",
    value: "",
  },
  {
    name: "writing-mode",
    nameForTitle: "Writing",
    value: "",
  },
  {
    name: "zoom",
    nameForTitle: "Zoom",
    value: "",
  },
];
const AlignGroup: StyleGroup = {
  groupName: "Alignment",
  propertyNames: ["align-content", "align-items", "align-self"],
  groups: [
    {
      name: "align-content",
      nameForTitle: "Align Content",
      type: "string",
      description:
        "Aligns the flex container's lines within the flex container when there is extra space on the cross-axis",
      value: "",
      options: [
        "normal",
        "start",
        "center",
        "end",
        "flex-start",
        "flex-end",
        "baseline",
        "first baseline",
        "last baseline",
        "space-between",
        "space-around",
        "space-evenly",
        "stretch",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
    {
      name: "align-items",
      nameForTitle: "Align Items",
      type: "string",
      description:
        "Aligns flex items along the cross-axis of the current line of the flex container",
      value: "",
      options: [
        "normal",
        "stretch",
        "center",
        "start",
        "end",
        "flex-start",
        "flex-end",
        "self-start",
        "self-end",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
    {
      name: "align-self",
      nameForTitle: "Align Self",
      type: "string",
      description:
        "Allows the default alignment (or the one specified by align-items) to be overridden for individual flex items",
      value: "",
      options: [
        "auto",
        "normal",
        "center",
        "start",
        "end",
        "self-start",
        "self-end",
        "flex-start",
        "flex-end",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "stretch",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
  ],
};
const AllGroup: StyleGroup = {
  groupName: "All",
  propertyNames: ["all"],
  groups: [
    {
      name: "all",
      nameForTitle: "All Property",
      type: "string",
      description: "Applies all styles to an element.",
      value: "",
      options: [...globalCssOptions],
    },
  ],
};
const BackfaceVisibilityGroup: StyleGroup = {
  groupName: "Backface Visibility",
  propertyNames: ["backface-visibility"],
  groups: [
    {
      name: "backface-visibility",
      nameForTitle: "Backface Visibility",
      type: "string",
      description: "Determines whether the back face of an element is visible when turned.",
      value: "",
      options: ["visible", "hidden"],
    },
  ],
};
const BackgroundGroup: StyleGroup = {
  groupName: "Background",
  propertyNames: [
    "background",
    "background-color",
    "background-attachment",
    "background-blend-mode",
    "background-clip",
    "background-image",
    "background-origin",
    "background-position",
    "background-position-x",
    "background-position-y",
    "background-repeat",
    "background-size",
  ],
  groups: [
    {
      name: "background-attachment",
      nameForTitle: "Background Attachment",
      type: "string",
      description:
        "Specifies whether the background image is fixed or scrolls with the rest of the page",
      value: "",
      maxOptionCounts: 2,
      options: ["scroll", "fixed", "local", ...globalCssOptions],
    },
    {
      name: "background-blend-mode",
      nameForTitle: "Background Blend Mode",
      type: "string",
      description: "Specifies the blending mode of the background images",
      value: "",
      maxOptionCounts: 2,
      options: [
        "normal",
        "multiply",
        "screen",
        "overlay",
        "darken",
        "lighten",
        "color-dodge",
        "color-burn",
        "hard-light",
        "soft-light",
        "difference",
        "exclusion",
        "hue",
        "saturation",
        "color",
        "luminosity",
        ...globalCssOptions,
      ],
    },
    {
      name: "background-clip",
      nameForTitle: "Background Clip",
      type: "string",
      description: "Specifies the painting area of the background",
      value: "",
      options: ["border-box", "padding-box", "content-box", "text", ...globalCssOptions],
    },
    {
      name: "background-color",
      nameForTitle: "Background Color",
      type: "string",
      description: "Color styles for the element's background",
      value: "",
      options: ["color", ...globalCssOptions],
    },
    {
      name: "background-image",
      nameForTitle: "Background Image",
      type: "string",
      description: "Specifies the background image",
      value: "",
      options: ["none", ...globalCssOptions], // url(), linear gradient()
    },
    {
      name: "background-origin",
      nameForTitle: "Background Origin",
      type: "string",
      description: "Specifies the origin position of the background image",
      value: "",
      options: ["border-box", "padding-box", "content-box", ...globalCssOptions],
    },
    {
      name: "background-position-x",
      nameForTitle: "Background Position X",
      type: "string",
      description: "Specifies the x-coordinate of the background image",
      value: "",
      options: ["left", "center", "right", "length", ...globalCssOptions],
    },
    {
      name: "background-position-y",
      nameForTitle: "Background Position Y",
      type: "string",
      description: "Specifies the y-coordinate of the background image",
      value: "",
      options: ["top", "center", "bottom", "length", ...globalCssOptions],
    },
    {
      name: "background-repeat",
      nameForTitle: "Background Repeat",
      type: "string",
      description: "Specifies how the background image repeats",
      value: "",
      maxOptionCounts: 2,
      options: [
        "repeat",
        "repeat-x",
        "repeat-y",
        "no-repeat",
        "space",
        "round",
        ...globalCssOptions,
      ],
    },
    {
      name: "background-size",
      nameForTitle: "Background Size",
      type: "string",
      description: "Specifies the size of the background image",
      value: "",
      options: ["auto", "cover", "contain", "length", ...globalCssOptions],
    },
  ],
};
const BlockSizeGroup: StyleGroup = {
  groupName: "Block-Size",
  propertyNames: ["block-size", "min-block-size", "max-block-size"],
  groups: [
    {
      name: "block-size",
      nameForTitle: "Block-Size",
      type: "string",
      description: "Sets the width of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "min-block-size",
      nameForTitle: "Minimum Block-Size",
      type: "string",
      description: "Sets the minimum width of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "max-block-size",
      nameForTitle: "Maximum Block-Size",
      type: "string",
      description: "Sets the maximum width of an element.",
      value: "",
      options: ["none", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
  ],
};
const BoxGroup: StyleGroup = {
  groupName: "Box",
  propertyNames: ["-webkit-box-decoration-break", "box-shadow", "box-sizing"],
  groups: [
    {
      name: "-webkit-box-decoration-break",
      nameForTitle: "Box Decoration Break",
      type: "string",
      description:
        "Specifies how an element's fragments should be rendered when broken across multiple lines, columns, or pages.",
      value: "",
      options: ["slice", "clone", ...globalCssOptions],
    },
    {
      name: "box-shadow",
      nameForTitle: "Box Shadow",
      type: "string",
      description: "Adds shadow effects around the box.",
      value: "",
      options: ["none", "length", "color"],
    },
    {
      name: "box-sizing",
      nameForTitle: "Box Sizing",
      type: "string",
      description: "Defines how the width and height of the element are calculated.",
      value: "",
      options: ["content-box", "border-box", ...globalCssOptions],
    },
  ],
};
const BreakGroup: StyleGroup = {
  groupName: "Break",
  propertyNames: ["break-after", "break-before", "break-inside"],
  groups: [
    {
      name: "break-after",
      nameForTitle: "Break After",
      type: "string",
      description: "Specifies how page, column, or region breaks should occur after an element.",
      value: "",
      options: [
        "all",
        "always",
        "auto",
        "avoid",
        "avoid-page",
        "avoid-column",
        "avoid-region",
        "page",
        "left",
        "right",
        "recto",
        "verso",
        "column",
        "region",
        ...globalCssOptions,
      ],
    },
    {
      name: "break-before",
      nameForTitle: "Break Before",
      type: "string",
      description: "Specifies how page, column, or region breaks should occur before an element.",
      value: "",
      options: [
        "all",
        "always",
        "auto",
        "avoid",
        "avoid-page",
        "avoid-column",
        "avoid-region",
        "page",
        "left",
        "right",
        "recto",
        "verso",
        "column",
        "region",
        ...globalCssOptions,
      ],
    },
    {
      name: "break-inside",
      nameForTitle: "Break Inside",
      type: "string",
      description: "Specifies how page, column, or region breaks should occur inside an element.",
      value: "",
      options: ["auto", "avoid", "avoid-page", "avoid-column", "avoid-region", ...globalCssOptions],
    },
  ],
};
const ColorGroup: StyleGroup = {
  groupName: "Color",
  propertyNames: ["accent-color", "caret-color", "color", "color-scheme"],
  groups: [
    {
      name: "accent-color",
      nameForTitle: "Accent Color",
      type: "string",
      description:
        "Sets the accent color for user interface controls generated by the element, such as form control elements and progress bars.",
      value: "",
      options: ["auto", "color", ...globalCssOptions],
    },
    {
      name: "caret-color",
      nameForTitle: "Caret Color",
      type: "color",
      description: "Sets the color of the text input cursor (caret).",
      value: "",
      options: ["auto", "color", ...globalCssOptions],
    },
    {
      name: "color",
      nameForTitle: "Color",
      type: "string",
      description: "Defines the color of the text for the element.",
      value: "",
      options: ["color", ...globalCssOptions],
    },
    {
      name: "color-scheme",
      nameForTitle: "Color Scheme",
      type: "string",
      description:
        "Specifies the preferred color scheme for the element, allowing for light and dark modes.",
      value: "",
      options: ["normal", "light", "dark", "light dark", "only light", ...globalCssOptions],
    },
  ],
};
const ColumnGroup: StyleGroup = {
  groupName: "Column and Row",
  propertyNames: [
    "column-count",
    "column-fill",
    "column-gap",
    "row-gap",
    "column-rule-color",
    "column-rule-style",
    "column-rule-width",
    "column-span",
    "column-width",
  ],
  groups: [
    {
      name: "column-count",
      nameForTitle: "Column Count",
      type: "number",
      description: "Specifies the number of columns an element should be divided into.",
      value: "",
      options: ["auto", "number", ...globalCssOptions],
    },
    {
      name: "column-fill",
      nameForTitle: "Column Fill",
      type: "string",
      description: "Specifies how the columns are filled.",
      value: "",
      options: ["auto", "balance", ...globalCssOptions],
    },
    {
      name: "column-gap",
      nameForTitle: "Column Gap",
      type: "string",
      description: "Specifies the gap between columns.",
      value: "",
      options: ["length", "normal", ...globalCssOptions],
    },
    {
      name: "row-gap",
      nameForTitle: "Row Gap",
      type: "length",
      description: "Specifies the gap between rows in a grid layout.",
      value: "",
      options: ["length", "normal", ...globalCssOptions],
    },
    {
      name: "column-rule-color",
      nameForTitle: "Column Rule Color",
      type: "string",
      description: "Specifies the color of the rule between columns.",
      value: "",
      options: ["color", ...globalCssOptions],
    },
    {
      name: "column-rule-style",
      nameForTitle: "Column Rule Style",
      type: "string",
      description: "Specifies the style of the rule between columns.",
      value: "",
      options: [
        "none",
        "hidden",
        "solid",
        "dotted",
        "dashed",
        "double",
        "groove",
        "ridge",
        "inset",
        "outset",
        ...globalCssOptions,
      ],
    },
    {
      name: "column-rule-width",
      nameForTitle: "Column Rule Width",
      type: "string",
      description: "Specifies the width of the rule between columns.",
      value: "",
      options: ["thin", "medium", "thick", "length", ...globalCssOptions],
    },
    {
      name: "column-span",
      nameForTitle: "Column Span",
      type: "string",
      description: "Specifies how many columns an element should span.",
      value: "",
      options: ["none", "all", ...globalCssOptions],
    },
    {
      name: "column-width",
      nameForTitle: "Column Width",
      type: "string",
      description: "Specifies the ideal width of the columns.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
  ],
};
const ContainGroup: StyleGroup = {
  groupName: "Contain",
  propertyNames: [
    "contain",
    "contain-intrinsic-block-size",
    "contain-intrinsic-height",
    "contain-intrinsic-inline-size",
    "contain-intrinsic-width",
  ],
  groups: [
    {
      name: "contain",
      nameForTitle: "Contain",
      type: "string",
      description: "Specifies the extent of containment of an element.",
      value: "",
      options: [
        "none",
        "strict",
        "content",
        "size",
        "inline-size",
        "layout",
        "style",
        "paint",
        ...globalCssOptions,
      ],
    },
    {
      name: "contain-intrinsic-block-size",
      nameForTitle: "Contain Intrinsic Block Size",
      type: "string",
      description: "Specifies the intrinsic block size of an element when containment is applied.",
      value: "",
      options: ["length", "none", ...globalCssOptions],
    },
    {
      name: "contain-intrinsic-height",
      nameForTitle: "Contain Intrinsic Height",
      type: "string",
      description: "Specifies the intrinsic height of an element when containment is applied.",
      value: "",
      options: ["length", "none", ...globalCssOptions],
    },
    {
      name: "contain-intrinsic-inline-size",
      nameForTitle: "Contain Intrinsic Inline Size",
      type: "string",
      description: "Specifies the intrinsic inline size of an element when containment is applied.",
      value: "",
      options: ["length", "none", ...globalCssOptions],
    },
    {
      name: "contain-intrinsic-width",
      nameForTitle: "Contain Intrinsic Width",
      type: "string",
      description: "Specifies the intrinsic width of an element when containment is applied.",
      value: "",
      options: ["length", "none", ...globalCssOptions],
    },
  ],
};
const ContentGroup: StyleGroup = {
  groupName: "Content",
  propertyNames: ["content", "content-visibility"],
  groups: [
    {
      name: "content",
      nameForTitle: "Content",
      type: "string",
      description:
        "Generates content to be inserted before or after an element's content using pseudo-elements.",
      value: "",
      options: ["none", "text", ...globalCssOptions], // url()
    },
    {
      name: "content-visibility",
      nameForTitle: "Content Visibility",
      type: "string",
      description:
        "Controls the visibility and rendering of an element's content, optimizing performance by skipping rendering when content is not visible.",
      value: "",
      options: [
        "auto", // The browser decides whether to render content based on visibility in the viewport.
        "hidden", // The content is not visible and will not be rendered.
        "visible", // The default value. The content is visible.
        ...globalCssOptions,
      ],
    },
  ],
};
const CursorGroup: StyleGroup = {
  groupName: "Cursor",
  propertyNames: ["cursor"],
  groups: [
    {
      name: "cursor",
      nameForTitle: "Cursor",
      type: "string",
      description: "Specifies the type of cursor to be displayed when pointing over an element.",
      value: "",
      options: [
        "auto",
        "default",
        "none",
        "context-menu",
        "help",
        "pointer",
        "progress",
        "wait",
        "cell",
        "crosshair",
        "text",
        "vertical-text",
        "alias",
        "copy",
        "move",
        "no-drop",
        "not-allowed",
        "grab",
        "grabbing",
        "e-resize",
        "n-resize",
        "ne-resize",
        "nw-resize",
        "s-resize",
        "se-resize",
        "sw-resize",
        "w-resize",
        "ew-resize",
        "ns-resize",
        "nesw-resize",
        "nwse-resize",
        "col-resize",
        "row-resize",
        "all-scroll",
        "zoom-in",
        "zoom-out",
        ...globalCssOptions,
      ],
    },
  ],
};
const DisplayGroup: StyleGroup = {
  groupName: "Display",
  propertyNames: ["appearance", "display", "opacity", "visibility"],
  groups: [
    {
      name: "appearance",
      nameForTitle: "Appearance",
      type: "string",
      description: "Defines the appearance of an element, including how it should look by default.",
      value: "",
      options: [
        "auto",
        "button",
        "checkbox",
        "listbox",
        "menulist ",
        "menulist-button",
        "meter",
        "none",
        "progress-bar",
        "radio",
        "searchfield",
        "textarea",
        "textfield",
      ],
    },
    {
      name: "display",
      nameForTitle: "Display",
      type: "string",
      description: "Specifies the display behavior of an element.",
      value: "",
      options: [
        "block",
        "inline",
        "inline-block",
        "flex",
        "inline-flex",
        "grid",
        "inline-grid",
        "flow-root",
        "none",
        "contents",
        "table",
        "table-row",
        "table-cell",
        "table-row-group",
        "table-header-group",
        "table-footer-group",
        "table-column-group",
        "table-column",
        "table-caption",
        "list-item",
        "ruby",
        "ruby-base",
        "ruby-text",
        "ruby-base-container",
        "ruby-text-container",
        ...globalCssOptions,
      ],
    },
    {
      name: "opacity",
      nameForTitle: "Opacity",
      type: "string",
      description: "Specifies the opacity level of an element.",
      value: "",
      options: ["number", ...globalCssOptions],
    },
    {
      name: "visibility",
      nameForTitle: "Visibility",
      type: "string",
      description: "Specifies whether an element is visible or not.",
      value: "",
      options: ["visible", "hidden", "collapse", ...globalCssOptions],
    },
  ],
};
const FlexGroup: StyleGroup = {
  groupName: "Flex",
  propertyNames: [
    "flex-basis",
    "flex-direction",
    "flex-flow",
    "flex-grow",
    "flex-shrink",
    "flex-wrap",
  ],
  groups: [
    {
      name: "flex-basis",
      nameForTitle: "Flex Basis",
      type: "string",
      description: "Specifies the initial main size of a flex item",
      value: "",
      options: [
        "auto",
        "content",
        "min-content",
        "max-content",
        "fit-content",
        "length",
        ...globalCssOptions,
      ],
    },
    {
      name: "flex-direction",
      nameForTitle: "Flex Direction",
      type: "string",
      description: "Defines the direction of the flex container's main axis",
      value: "",
      options: ["row", "row-reverse", "column", "column-reverse", ...globalCssOptions],
    },
    {
      name: "flex-flow",
      nameForTitle: "Flex Flow",
      type: "string",
      description: "A shorthand property for the flex-direction and flex-wrap properties",
      value: "",
      maxOptionCounts: 2,
      options: [
        "row",
        "row-reverse",
        "column",
        "column-reverse",
        "nowrap",
        "wrap",
        "wrap-reverse",
        ...globalCssOptions,
      ],
    },
    {
      name: "flex-grow",
      nameForTitle: "Flex Grow",
      type: "string",
      description:
        "Specifies how much a flex item will grow relative to the rest of the flex items",
      value: "",
      options: ["number", ...globalCssOptions],
    },
    {
      name: "flex-shrink",
      nameForTitle: "Flex Shrink",
      type: "string",
      description:
        "Specifies how much a flex item will shrink relative to the rest of the flex items",
      value: "",
      options: ["number", ...globalCssOptions],
    },
    {
      name: "flex-wrap",
      nameForTitle: "Flex Wrap",
      type: "string",
      description:
        "Specifies whether flex items are forced into a single line or can be wrapped onto multiple lines",
      value: "",
      options: ["nowrap", "wrap", "wrap-reverse", ...globalCssOptions],
    },
  ],
};
const FloatGroup: StyleGroup = {
  groupName: "Float",
  propertyNames: ["float", "clear"],
  groups: [
    {
      name: "float",
      nameForTitle: "Float",
      type: "string",
      description: "Specifies how an element should float within its container.",
      value: "",
      options: ["none", "left", "right", "inline-start", "inline-end", ...globalCssOptions],
    },
    {
      name: "clear",
      nameForTitle: "Clear",
      type: "string",
      description:
        "Specifies which sides of an element's box are not affected by floating elements.",
      value: "",
      options: ["none", "left", "right", "both", "inline-start", "inline-end", ...globalCssOptions],
    },
  ],
};
const HeightGroup: StyleGroup = {
  groupName: "Height",
  propertyNames: ["height", "min-height", "max-height"],
  groups: [
    {
      name: "height",
      nameForTitle: "Height",
      type: "string",
      description: "Sets the height of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "min-height",
      nameForTitle: "Minimum Height",
      type: "string",
      description: "Sets the minimum height of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "max-height",
      nameForTitle: "Maximum Height",
      type: "string",
      description: "Sets the maximum height of an element.",
      value: "",
      options: ["none", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
  ],
};
const InlineSizeGroup: StyleGroup = {
  groupName: "Inline-Size",
  propertyNames: ["inline-size", "min-inline-size", "max-inline-size"],
  groups: [
    {
      name: "inline-size",
      nameForTitle: "Inline-Size",
      type: "string",
      description: "Sets the width of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "min-inline-size",
      nameForTitle: "Minimum Inline-Size",
      type: "string",
      description: "Sets the minimum width of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "max-inline-size",
      nameForTitle: "Maximum Inline-Size",
      type: "string",
      description: "Sets the maximum width of an element.",
      value: "",
      options: ["none", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
  ],
};
const JustifyGroup: StyleGroup = {
  groupName: "Justify",
  propertyNames: ["justify-content", "justify-items", "justify-self"],
  groups: [
    {
      name: "justify-content",
      nameForTitle: "Justify Content",
      type: "string",
      description:
        "Aligns the flexible container's items when the items do not use all available space on the main-axis.",
      value: "",
      options: [
        "flex-start",
        "flex-end",
        "center",
        "normal",
        "space-between",
        "space-around",
        "space-evenly",
        "stretch",
        "safe center",
        "unsafe center",
        "start",
        "end",
        "left",
        "right",
        ...globalCssOptions,
      ],
    },
    {
      name: "justify-items",
      nameForTitle: "Justify Items",
      type: "string",
      description:
        "Defines the default justify-self for all items of the box, giving them all a default way of justifying each box along the appropriate axis.",
      value: "",
      options: [
        "normal",
        "start",
        "end",
        "flex-start",
        "flex-end",
        "self-start",
        "self-end",
        "center",
        "left",
        "right",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "stretch",
        "safe center",
        "unsafe center",
        "safe",
        "unsafe",
        ...globalCssOptions,
      ],
    },
    {
      name: "justify-self",
      nameForTitle: "Justify Self",
      type: "string",
      description: "Aligns the selected item inside the flex container along the main axis.",
      value: "",
      options: [
        "auto",
        "normal",
        "start",
        "end",
        "flex-start",
        "flex-end",
        "center",
        "left",
        "right",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "stretch",
        "safe center",
        "unsafe center",
        "safe",
        "unsafe",
        ...globalCssOptions,
      ],
    },
  ],
};
const LineGroup: StyleGroup = {
  groupName: "Line",
  propertyNames: ["line-break", "-webkit-line-clamp", "line-height", "line-height-step"],
  groups: [
    {
      name: "line-break",
      nameForTitle: "Line Break",
      type: "string",
      description: "Specifies how or if to break lines within text.",
      value: "",
      options: ["auto", "loose", "normal", "strict", "anywhere", ...globalCssOptions],
    },
    {
      name: "-webkit-line-clamp",
      nameForTitle: "Line Clamp",
      type: "string",
      description:
        "Sets the amount of space used for lines, such as in the case of multiple lines of text.",
      value: "",
      options: ["number", ...globalCssOptions],
    },
    {
      name: "line-height",
      nameForTitle: "Line Height",
      type: "string",
      description:
        "Sets the amount of space used for lines, such as in the case of multiple lines of text.",
      value: "",
      options: ["normal", "number", "length", ...globalCssOptions],
    },
    {
      name: "line-height-step",
      nameForTitle: "Line Height Step",
      type: "string",
      description:
        "Sets the step size for line height, controlling the spacing between lines of text.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
  ],
};
const ListGroup: StyleGroup = {
  groupName: "List",
  propertyNames: ["list-style-image", "list-style-position", "list-style-type"],
  groups: [
    {
      name: "list-style-image",
      nameForTitle: "List Style Image",
      type: "string",
      description: "Sets an image as the list item marker.",
      value: "",
      options: ["none", ...globalCssOptions], //url()
    },
    {
      name: "list-style-position",
      nameForTitle: "List Style Position",
      type: "string",
      description:
        "Sets whether the list item markers should appear inside or outside the content flow.",
      value: "",
      options: ["inside", "outside", ...globalCssOptions],
    },
    {
      name: "list-style-type",
      nameForTitle: "List Style Type",
      type: "string",
      description: "Sets the marker (bullet) style for a list item.",
      value: "",
      options: [
        "none",
        "disc",
        "circle",
        "square",
        "decimal",
        "cjk-decimal",
        "decimal-leading-zero",
        "lower-roman",
        "upper-roman",
        "lower-greek",
        "lower-alpha",
        "lower-latin",
        "upper-alpha",
        "upper-latin",
        "arabic-indic",
        "-moz-arabic-indic",
        "armenian",
        "bengali",
        "-moz-bengali",
        "cambodian",
        "khmer",
        "cjk-earthly-branch",
        "-moz-cjk-earthly-branch",
        "cjk-heavenly-stem",
        "-moz-cjk-heavenly-stem",
        "cjk-ideographic",
        "devanagari",
        "-moz-devanagari",
        "ethiopic-numeric",
        "georgian",
        "gujarati",
        "-moz-gujarati",
        "gurmukhi",
        "-moz-gurmukhi",
        "hebrew",
        "hiragana",
        "hiragana-iroha",
        "japanese-formal",
        "japanese-informal",
        "kannada",
        "-moz-kannada",
        "katakana",
        "katakana-iroha",
        "korean-hangul-formal",
        "korean-hanja-formal",
        "korean-hanja-informal",
        "lao",
        "-moz-lao",
        "lower-armenian",
        "malayalam",
        "-moz-malayalam",
        "mongolian",
        "myanmar",
        "-moz-myanmar",
        "oriya",
        "-moz-oriya",
        "persian",
        "-moz-persian",
        "simp-chinese-formal",
        "simp-chinese-informal",
        "tamil",
        "-moz-tamil",
        "telugu",
        "-moz-telugu",
        "thai",
        "-moz-thai",
        "tibetan",
        "trad-chinese-formal",
        "trad-chinese-informal",
        "upper-armenian",
        "disclosure-open",
        "disclosure-closed",
        "-moz-ethiopic-halehame",
        "-moz-ethiopic-halehame-am",
        "-moz-ethiopic-halehame-ti-er",
        "-moz-ethiopic-halehame-ti-et",
        "-moz-ethiopic-numeric",
        "-moz-hangul",
        "-moz-hangul-consonant",
        "-moz-urdu",
        ...globalCssOptions,
      ],
    },
  ],
};
const MarginGroup: StyleGroup = {
  groupName: "Margin",
  propertyNames: [
    "margin-block-end",
    "margin-block-start",
    "margin-bottom",
    "margin-inline-end",
    "margin-inline-start",
    "margin-left",
    "margin-right",
    "margin-top",
  ],
  groups: [
    {
      name: "margin-block-end",
      nameForTitle: "Margin Block End",
      type: "string",
      description: "Defines the logical block-end margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-block-start",
      nameForTitle: "Margin Block Start",
      type: "string",
      description: "Defines the logical block-start margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-bottom",
      nameForTitle: "Margin Bottom",
      type: "string",
      description: "Sets the margin area on the bottom of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-inline-end",
      nameForTitle: "Margin Inline End",
      type: "string",
      description: "Defines the logical inline-end margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-inline-start",
      nameForTitle: "Margin Inline Start",
      type: "string",
      description: "Defines the logical inline-start margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-left",
      nameForTitle: "Margin Left",
      type: "string",
      description: "Sets the margin area on the left side of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-right",
      nameForTitle: "Margin Right",
      type: "string",
      description: "Sets the margin area on the right side of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-top",
      nameForTitle: "Margin Top",
      type: "string",
      description: "Sets the margin area on the top of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
  ],
};
const OutlineGroup: StyleGroup = {
  groupName: "Outline",
  propertyNames: ["outline-color", "outline-offset", "outline-style", "outline-width"],
  groups: [
    {
      name: "outline-color",
      nameForTitle: "Outline Color",
      type: "color",
      description: "Sets the color of an element's outline.",
      value: "",
      options: ["color", ...globalCssOptions],
    },
    {
      name: "outline-offset",
      nameForTitle: "Outline Offset",
      type: "string",
      description: "Sets the space between an outline and the edge or border of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "outline-style",
      nameForTitle: "Outline Style",
      type: "string",
      description: "Sets the style of an element's outline.",
      value: "",
      options: [
        "auto",
        "none",
        "dotted",
        "dashed",
        "solid",
        "double",
        "groove",
        "ridge",
        "inset",
        "outset",
        ...globalCssOptions,
      ],
    },
    {
      name: "outline-width",
      nameForTitle: "Outline Width",
      type: "string",
      description: "Sets the width of an element's outline.",
      value: "",
      options: ["thin", "medium", "thick", "length", ...globalCssOptions],
    },
  ],
};
const OverflowGroup: StyleGroup = {
  groupName: "Overflow",
  propertyNames: [
    "overflow-anchor",
    "overflow-block",
    "overflow-clip-margin",
    "overflow-inline",
    "overflow-wrap",
    "overflow-x",
    "overflow-y",
  ],
  groups: [
    {
      name: "overflow-anchor",
      nameForTitle: "Overflow Anchor",
      type: "string",
      description: "Prevents content shifts that users don't expect.",
      value: "",
      options: ["auto", "none", ...globalCssOptions],
    },
    {
      name: "overflow-block",
      nameForTitle: "Overflow Block",
      type: "string",
      description: "Controls how content overflows the block axis.",
      value: "",
      options: ["auto", "clip", "hidden", "scroll", "visible", ...globalCssOptions],
    },
    {
      name: "overflow-clip-margin",
      nameForTitle: "Overflow Clip Margin",
      type: "string",
      description: "Sets the margin to apply before clipping an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "overflow-inline",
      nameForTitle: "Overflow Inline",
      type: "string",
      description: "Controls how content overflows the inline axis.",
      value: "",
      options: ["auto", "clip", "hidden", "scroll", "visible", ...globalCssOptions],
    },
    {
      name: "overflow-wrap",
      nameForTitle: "Overflow Wrap",
      type: "string",
      description:
        "Specifies whether the browser should break lines inside an otherwise unbreakable string to prevent overflow.",
      value: "",
      options: ["normal", "break-word", "anywhere", ...globalCssOptions],
    },
    {
      name: "overflow-x",
      nameForTitle: "Overflow X",
      type: "string",
      description:
        "Specifies what to do with the left/right edges of the content when it overflows the element's content area.",
      value: "",
      options: ["auto", "clip", "hidden", "scroll", "visible", ...globalCssOptions],
    },
    {
      name: "overflow-y",
      nameForTitle: "Overflow Y",
      type: "string",
      description:
        "Specifies what to do with the top/bottom edges of the content when it overflows the element's content area.",
      value: "",
      options: ["auto", "clip", "hidden", "scroll", "visible", ...globalCssOptions],
    },
  ],
};
const OverscrollGroup: StyleGroup = {
  groupName: "Overscroll",
  propertyNames: [
    "overscroll-behavior-x",
    "overscroll-behavior-y",
    "overscroll-behavior-block",
    "overscroll-behavior-inline",
  ],
  groups: [
    {
      name: "overscroll-behavior-x",
      nameForTitle: "Overscroll Behavior X",
      type: "string",
      description: "Specifies the overscroll behavior for the x-axis.",
      value: "",
      options: ["auto", "contain", "none", ...globalCssOptions],
    },
    {
      name: "overscroll-behavior-y",
      nameForTitle: "Overscroll Behavior Y",
      type: "string",
      description: "Specifies the overscroll behavior for the y-axis.",
      value: "",
      options: ["auto", "contain", "none", ...globalCssOptions],
    },
    {
      name: "overscroll-behavior-block",
      nameForTitle: "Overscroll Behavior Block",
      type: "string",
      description: "Specifies the overscroll behavior for block-level elements.",
      value: "",
      options: ["auto", "contain", "none", ...globalCssOptions],
    },
    {
      name: "overscroll-behavior-inline",
      nameForTitle: "Overscroll Behavior Inline",
      type: "string",
      description: "Specifies the overscroll behavior for inline-level elements.",
      value: "",
      options: ["auto", "contain", "none", ...globalCssOptions],
    },
  ],
};
const PaddingGroup: StyleGroup = {
  groupName: "Padding",
  propertyNames: [
    "padding-block-end",
    "padding-block-start",
    "padding-bottom",
    "padding-inline-end",
    "padding-inline-start",
    "padding-left",
    "padding-right",
    "padding-top",
  ],
  groups: [
    {
      name: "padding-block-end",
      nameForTitle: "Padding Block End",
      type: "string",
      description: "Defines the logical block-end padding of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "padding-block-start",
      nameForTitle: "Padding Block Start",
      type: "string",
      description: "Defines the logical block-start padding of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "padding-bottom",
      nameForTitle: "Padding Bottom",
      type: "string",
      description: "Sets the padding area on the bottom of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "padding-inline-end",
      nameForTitle: "Padding Inline End",
      type: "string",
      description: "Defines the logical inline-end padding of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "padding-inline-start",
      nameForTitle: "Padding Inline Start",
      type: "string",
      description: "Defines the logical inline-start padding of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "padding-left",
      nameForTitle: "Padding Left",
      type: "string",
      description: "Sets the padding area on the left side of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "padding-right",
      nameForTitle: "Padding Right",
      type: "string",
      description: "Sets the padding area on the right side of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
    {
      name: "padding-top",
      nameForTitle: "Padding Top",
      type: "string",
      description: "Sets the padding area on the top of an element.",
      value: "",
      options: ["length", ...globalCssOptions],
    },
  ],
};
const PlaceGroup: StyleGroup = {
  groupName: "Place",
  propertyNames: ["place-content", "place-items", "place-self"],
  groups: [
    {
      name: "place-content",
      nameForTitle: "Place Content",
      type: "string",
      description:
        "Shorthand for align-content and justify-content. Defines the alignment of items within a container.",
      value: "",
      maxOptionCounts: 2,
      options: [
        "start",
        "end",
        "center",
        "flex-start",
        "flex-end",
        "normal",
        "stretch",
        "space-between",
        "space-around",
        "space-evenly",
        "baseline",
        "first baseline",
        "last baseline",
        "safe",
        "unsafe",
        ...globalCssOptions,
      ],
    },
    {
      name: "place-items",
      nameForTitle: "Place Items",
      type: "string",
      description:
        "Shorthand for align-items and justify-items. Defines the alignment of items within a container.",
      value: "",
      maxOptionCounts: 2,
      options: [
        "start",
        "end",
        "center",
        "flex-start",
        "flex-end",
        "self-start",
        "self-end",
        "normal",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "stretch",
        "space-between",
        "space-around",
        "space-evenly",
        "safe",
        "unsafe",
        ...globalCssOptions,
      ],
    },
    {
      name: "place-self",
      nameForTitle: "Place Self",
      type: "string",
      description:
        "Shorthand for align-self and justify-self. Defines the alignment of an individual item within a container.",
      value: "",
      maxOptionCounts: 2,
      options: [
        "auto",
        "start",
        "end",
        "center",
        "flex-start",
        "flex-end",
        "self-start",
        "self-end",
        "normal",
        "anchor-center",
        "stretch",
        "baseline",
        "first baseline",
        "last baseline",
        "safe",
        "unsafe",
        ...globalCssOptions,
      ],
    },
  ],
};
const PositionGroup: StyleGroup = {
  groupName: "Position",
  propertyNames: ["position", "top", "right", "bottom", "left", "z-index"],
  groups: [
    {
      name: "position",
      nameForTitle: "Position",
      type: "string",
      description: "Specifies the type of positioning method used for an element.",
      value: "",
      options: ["static", "relative", "absolute", "fixed", "sticky", ...globalCssOptions],
    },
    {
      name: "top",
      nameForTitle: "Top",
      type: "string",
      description: "Specifies the top offset of a positioned element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "right",
      nameForTitle: "Right",
      type: "string",
      description: "Specifies the right offset of a positioned element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "bottom",
      nameForTitle: "Bottom",
      type: "string",
      description: "Specifies the bottom offset of a positioned element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "left",
      nameForTitle: "Left",
      type: "string",
      description: "Specifies the left offset of a positioned element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "z-index",
      nameForTitle: "Z-Index",
      type: "number",
      description: "Specifies the stack order of a positioned element.",
      value: "",
      options: ["auto", "number", ...globalCssOptions],
    },
  ],
};
const ScrollbarGroup: StyleGroup = {
  groupName: "Scrollbar",
  propertyNames: ["scrollbar-color", "scrollbar-gutter", "scrollbar-width"],
  groups: [
    {
      name: "scrollbar-color",
      nameForTitle: "Scrollbar Color",
      type: "string",
      description: "Sets the color of the scrollbar track and thumb.",
      value: "",
      options: ["auto", "color", ...globalCssOptions],
    },
    {
      name: "scrollbar-gutter",
      nameForTitle: "Scrollbar Gutter",
      type: "string",
      description: "Controls the presence of scrollbar gutters.",
      value: "",
      options: ["auto", "stable", "stable both-edges", ...globalCssOptions],
    },
    {
      name: "scrollbar-width",
      nameForTitle: "Scrollbar Width",
      type: "string",
      description: "Sets the width of the scrollbar.",
      value: "",
      options: ["auto", "none", "thin", ...globalCssOptions],
    },
  ],
};
const TableGroup: StyleGroup = {
  groupName: "Table",
  propertyNames: ["empty-cells", "caption-side", "table-layout"],
  groups: [
    {
      name: "caption-side",
      nameForTitle: "Caption Side",
      type: "string",
      description: "Specifies the placement of the caption for a table element.",
      value: "",
      options: ["top", "bottom", ...globalCssOptions],
    },
    {
      name: "empty-cells",
      nameForTitle: "Empty Cells",
      type: "string",
      description:
        "Specifies whether to display or hide borders and backgrounds of empty table cells.",
      value: "",
      options: ["show", "hide", ...globalCssOptions],
    },
    {
      name: "table-layout",
      nameForTitle: "Table Layout",
      type: "string",
      description: "Defines the algorithm used to lay out the table cells, rows, and columns.",
      value: "",
      options: ["auto", "fixed", ...globalCssOptions],
    },
  ],
};
const TextGroup: StyleGroup = {
  groupName: "Text",
  propertyNames: [
    "text-align",
    "text-align-last",
    "text-combine-upright",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-skip-ink",
    "text-decoration-style",
    "text-decoration-thickness",
    "text-emphasis-color",
    "text-emphasis-position",
    "text-emphasis-style",
    "text-indent",
    "text-justify",
    "text-orientation",
    "text-overflow",
    "text-rendering",
    "text-shadow",
    "text-size-adjust",
    "text-spacing-trim",
    "text-transform",
    "text-underline-offset",
    "text-underline-position",
    "text-wrap",
    "text-wrap-mode",
    "text-wrap-style",
  ],
  groups: [
    {
      name: "text-align",
      nameForTitle: "Text Align",
      type: "string",
      description: "Defines the horizontal alignment of text within its containing block.",
      value: "",
      options: [
        "left",
        "right",
        "center",
        "justify",
        "justify-all",
        "start",
        "end",
        "match-parent",
        ...globalCssOptions,
      ],
    },
    {
      name: "text-align-last",
      nameForTitle: "Text Align Last",
      type: "string",
      description: "Specifies how the last line of a block or multi-line element is aligned.",
      value: "",
      options: ["auto", "left", "right", "center", "justify", "start", "end", ...globalCssOptions],
    },
    {
      name: "text-combine-upright",
      nameForTitle: "Text Combine Upright",
      type: "string",
      description:
        "Combines adjacent text characters vertically to produce the visual effect of upright text.",
      value: "",
      options: ["none", "all", ...globalCssOptions],
    },
    {
      name: "text-decoration-color",
      nameForTitle: "Text Decoration Color",
      type: "string",
      description: "Sets the color of text decoration lines.",
      value: "",
      options: ["color", ...globalCssOptions],
    },
    {
      name: "text-decoration-line",
      nameForTitle: "Text Decoration Line",
      type: "string",
      description: "Specifies which text decoration lines are used.",
      value: "",
      maxOptionCounts: 2,
      options: ["none", "underline", "overline", "line-through", "blink", ...globalCssOptions],
    },
    {
      name: "text-decoration-skip-ink",
      nameForTitle: "Text Decoration Skip Ink",
      type: "string",
      description:
        "Specifies whether the text decoration should skip the ink of the text, such as in certain fonts.",
      value: "",
      options: ["auto", "none", "all", ...globalCssOptions],
    },
    {
      name: "text-decoration-style",
      nameForTitle: "Text Decoration Style",
      type: "string",
      description: "Specifies the style of the text decoration line.",
      value: "",
      options: ["solid", "double", "dotted", "dashed", "wavy", ...globalCssOptions],
    },
    {
      name: "text-decoration-thickness",
      nameForTitle: "Text Decoration Thickness",
      type: "string",
      description: "Specifies the thickness of the text decoration line.",
      value: "",
      options: ["auto", "from-font", "length", ...globalCssOptions],
    },
    {
      name: "text-emphasis-color",
      nameForTitle: "Text Emphasis Color",
      type: "string",
      description: "Sets the color of the emphasis marks.",
      value: "",
      options: ["color", ...globalCssOptions],
    },
    {
      name: "text-emphasis-position",
      nameForTitle: "Text Emphasis Position",
      type: "string",
      description: "Specifies the position of the emphasis marks in relation to the text.",
      value: "",
      maxOptionCounts: 2,
      options: ["over", "under", "left", "right", ...globalCssOptions],
    },
    {
      name: "text-emphasis-style",
      nameForTitle: "Text Emphasis Style",
      type: "string",
      description: "Specifies the style of the emphasis marks.",
      value: "",
      options: [
        "none",
        "filled",
        "open",
        "dot",
        "circle",
        "double-circle",
        "triangle",
        "sesame",
        ...globalCssOptions,
      ], //"string"
    },
    {
      name: "text-indent",
      nameForTitle: "Text Indent",
      type: "string",
      description: "Specifies the indentation of the first line of text.",
      value: "",
      maxOptionCounts: 3,
      options: ["length", "each-line", "hanging", ...globalCssOptions],
    },
    {
      name: "text-justify",
      nameForTitle: "Text Justify",
      type: "string",
      description: "Defines how the text is justified when aligned.",
      value: "",
      options: ["auto", "inter-word", "inter-character", "none", ...globalCssOptions],
    },
    {
      name: "text-orientation",
      nameForTitle: "Text Orientation",
      type: "string",
      description: "Sets the orientation of text characters.",
      value: "",
      options: ["mixed", "upright", "sideways", "sideways-right", ...globalCssOptions],
    },
    {
      name: "text-overflow",
      nameForTitle: "Text Overflow",
      type: "string",
      description: "Specifies how the overflowed text should be displayed.",
      value: "",
      maxOptionCounts: 2,
      options: ["clip", "ellipsis", ...globalCssOptions], //"string -> notsupported yet on chrome"
    },
    {
      name: "text-rendering",
      nameForTitle: "Text Rendering",
      type: "string",
      description: "Defines how text should be rendered by the browser.",
      value: "",
      options: [
        "auto",
        "optimizeSpeed",
        "optimizeLegibility",
        "geometricPrecision",
        ...globalCssOptions,
      ],
    },
    {
      // need unique component. so add at future updates.
      name: "text-shadow",
      nameForTitle: "Text Shadow",
      type: "string",
      description: "Sets the shadow effect to apply to text.",
      value: "",
      options: ["none", "length", "color", ...globalCssOptions],
    },
    {
      name: "text-size-adjust",
      nameForTitle: "Text Size Adjust",
      type: "string",
      description:
        "Controls the adjustment of text size to improve readability on different devices.",
      value: "",
      options: ["auto", "none", "length", ...globalCssOptions],
    },
    {
      name: "text-spacing-trim",
      nameForTitle: "Text Spacing Trim",
      type: "string",
      description: "Sets the spacing of text characters and lines.",
      value: "",
      options: ["normal", "space-all", "space-first", "trim-start", ...globalCssOptions],
    },
    {
      name: "text-transform",
      nameForTitle: "Text Transform",
      type: "string",
      description: "Defines how text should be transformed, such as uppercase or lowercase.",
      value: "",
      options: ["none", "capitalize", "uppercase", "lowercase", ...globalCssOptions],
    },
    {
      name: "text-underline-offset",
      nameForTitle: "Text Underline Offset",
      type: "string",
      description: "Sets the offset of the underline relative to the text.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "text-underline-position",
      nameForTitle: "Text Underline Position",
      type: "string",
      description: "Specifies the position of the underline relative to the text.",
      value: "",
      maxOptionCounts: 2,
      options: ["auto", "under", "left", "right", ...globalCssOptions],
    },
    {
      name: "text-wrap",
      nameForTitle: "Text Wrap",
      type: "string",
      description: "Specifies the text wrapping mode.",
      value: "",
      options: ["wrap", "nowrap", "balance", "pretty", "stable", ...globalCssOptions],
    },
    {
      name: "text-wrap-mode",
      nameForTitle: "Text Wrap Mode",
      type: "string",
      description: "Specifies the text wrapping mode.",
      value: "",
      options: ["wrap", "nowrap", ...globalCssOptions],
    },
    {
      name: "text-wrap-style",
      nameForTitle: "Text Wrap Style",
      type: "string",
      description: "Sets the style of text wrapping.",
      value: "",
      options: ["auto", "balance", "pretty", "stable", ...globalCssOptions],
    },
  ],
};
const WhiteSpaceGroup: StyleGroup = {
  groupName: "White Space",
  propertyNames: ["white-space", "white-space-collapse"],
  groups: [
    {
      name: "white-space",
      nameForTitle: "White Space",
      type: "string",
      description: "Specifies how white space inside an element is handled.",
      value: "",
      options: [
        "normal",
        "nowrap",
        "pre",
        "pre-wrap",
        "pre-line",
        "break-spaces",
        ...globalCssOptions,
      ],
    },
    {
      name: "white-space-collapse",
      nameForTitle: "White Space Collapse",
      type: "string",
      description:
        "Controls the collapsing of white space in an element. Note that this property is experimental and not widely supported.",
      value: "",
      options: [
        "collapse",
        "preserve",
        "preserve-breaks",
        "preserve-spaces",
        "break-spaces",
        ...globalCssOptions,
      ],
    },
  ],
};
const WidthGroup: StyleGroup = {
  groupName: "Width",
  propertyNames: ["width", "min-width", "max-width"],
  groups: [
    {
      name: "width",
      nameForTitle: "Width",
      type: "string",
      description: "Sets the width of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "min-width",
      nameForTitle: "Minimum Width",
      type: "string",
      description: "Sets the minimum width of an element.",
      value: "",
      options: ["auto", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
    {
      name: "max-width",
      nameForTitle: "Maximum Width",
      type: "string",
      description: "Sets the maximum width of an element.",
      value: "",
      options: ["none", "length", "max-content", "min-content", "fit-content", ...globalCssOptions],
    },
  ],
};
const WordGroup: StyleGroup = {
  groupName: "Word",
  propertyNames: ["word-break", "word-spacing"],
  groups: [
    {
      name: "word-break",
      nameForTitle: "Word Break",
      type: "string",
      description: "Specifies how words should break when reaching the end of a line.",
      value: "",
      options: [
        "normal",
        "break-all",
        "keep-all",
        "auto-phrase",
        "break-word",
        ...globalCssOptions,
      ],
    },
    {
      name: "word-spacing",
      nameForTitle: "Word Spacing",
      type: "string",
      description: "Sets the spacing between words.",
      value: "",
      options: ["normal", "length", ...globalCssOptions],
    },
  ],
};
const WritingModeGroup: StyleGroup = {
  groupName: "Writing",
  propertyNames: ["writing-mode"],
  groups: [
    {
      name: "writing-mode",
      nameForTitle: "Writing Mode",
      type: "string",
      description: "Defines the direction and orientation of text.",
      value: "",
      options: [
        "horizontal-tb",
        "vertical-rl",
        "vertical-lr",
        "sideways-rl",
        "sideways-lr",
        ...globalCssOptions,
      ],
    },
  ],
};
const ZoomGroup: StyleGroup = {
  groupName: "Zoom",
  propertyNames: ["zoom"],
  groups: [
    {
      name: "zoom",
      nameForTitle: "Zoom",
      type: "string",
      description: "Defines the zoom level of the element.",
      value: "",
      options: ["length", "number", "normal", "reset", ...globalCssOptions],
    },
  ],
};

export const STYLE_GROUPS: StyleGroup[] = [
  AlignGroup,
  AllGroup,
  BackfaceVisibilityGroup,
  BackgroundGroup,
  BlockSizeGroup,
  BoxGroup,
  BreakGroup,
  ColorGroup,
  ColumnGroup,
  ContainGroup,
  ContentGroup,
  CursorGroup,
  DisplayGroup,
  FlexGroup,
  FloatGroup,
  HeightGroup,
  InlineSizeGroup,
  JustifyGroup,
  LineGroup,
  ListGroup,
  MarginGroup,
  OutlineGroup,
  OverflowGroup,
  OverscrollGroup,
  PaddingGroup,
  PlaceGroup,
  PositionGroup,
  ScrollbarGroup,
  TableGroup,
  TextGroup,
  WhiteSpaceGroup,
  WidthGroup,
  WordGroup,
  WritingModeGroup,
  ZoomGroup,
];
