import { Style, StyleGroup } from "@/types/styleTypes";
export const globalCssOptions = ["inherit", "initial", "revert", "revert-layer", "unset"];
export const customAndGlobalCssOptions = [
  "custom",
  "inherit",
  "initial",
  "revert",
  "revert-layer",
  "unset",
];
export const namedPositions = ["left", "right", "top", "bottom", "center"];
export const lengthUnits = [
  "px",
  "em",
  "rem",
  "cm",
  "mm",
  "in",
  "pt",
  "pc",
  "ch",
  "vw",
  "vh",
  "vmin",
  "vmax",
];
export const Length: Style = {
  name: "length",
  nameForTitle: "Length",
  type: "string",
  description: "Unit of lengths",
  value: "",
  options: [...lengthUnits],
};

export const GLOBAL_STYLES: Style[] = [
  {
    name: "background-color",
    description: "Color Styles for the element",
    value: "",
  },
  {
    name: "color",
    description: "Color Styles for the element",
    value: "",
  },
  {
    name: "color-scheme",
    description: "Color Styles for the element",
    value: "",
  },
];
const AlignGroup = {
  groupName: "Alignment Group",
  propertyNames: ["align-content", "align-items", "align-self"],
  groups: [
    {
      name: "align-content",
      nameForTitle: "Align Content",
      type: "string",
      description:
        "Aligns the flex container's lines within the flex container when there is extra space on the cross-axis",
      value: "",
      options: [
        "normal",
        "start",
        "center",
        "end",
        "flex-start",
        "flex-end",
        "baseline",
        "first baseline",
        "last baseline",
        "space-between",
        "space-around",
        "space-evenly",
        "stretch",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
    {
      name: "align-items",
      nameForTitle: "Align Items",
      type: "string",
      description:
        "Aligns flex items along the cross-axis of the current line of the flex container",
      value: "",
      options: [
        "normal",
        "stretch",
        "center",
        "start",
        "end",
        "flex-start",
        "flex-end",
        "self-start",
        "self-end",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
    {
      name: "align-self",
      nameForTitle: "Align Self",
      type: "string",
      description:
        "Allows the default alignment (or the one specified by align-items) to be overridden for individual flex items",
      value: "",
      options: [
        "auto",
        "normal",
        "center",
        "start",
        "end",
        "self-start",
        "self-end",
        "flex-start",
        "flex-end",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "stretch",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
  ],
};
const BackgroundGroup = {
  groupName: "Background Group",
  propertyNames: [
    "background",
    "background-color",
    "background-attachment",
    "background-blend-mode",
    "background-clip",
    "background-image",
    "background-origin",
    "background-position",
    "background-position-x",
    "background-position-y",
    "background-repeat",
    "background-size",
  ],
  groups: [
    {
      name: "background",
      nameForTitle: "Background",
      type: "string",
      description: "Shorthand for setting all background properties",
      value: "",
      options: [...customAndGlobalCssOptions],
    },
    {
      name: "background-attachment",
      nameForTitle: "Background Attachment",
      type: "string",
      description:
        "Specifies whether the background image is fixed or scrolls with the rest of the page",
      value: "",
      maxOptionCounts: 2,
      options: ["scroll", "fixed", "local", ...globalCssOptions],
    },
    {
      name: "background-blend-mode",
      nameForTitle: "Background Blend Mode",
      type: "string",
      description: "Specifies the blending mode of the background images",
      value: "",
      maxOptionCounts: 2,
      options: [
        "normal",
        "multiply",
        "screen",
        "overlay",
        "darken",
        "lighten",
        "color-dodge",
        "color-burn",
        "hard-light",
        "soft-light",
        "difference",
        "exclusion",
        "hue",
        "saturation",
        "color",
        "luminosity",
        ...globalCssOptions,
      ],
    },
    {
      name: "background-clip",
      nameForTitle: "Background Clip",
      type: "string",
      description: "Specifies the painting area of the background",
      value: "",
      options: ["border-box", "padding-box", "content-box", "text", ...globalCssOptions],
    },
    {
      name: "background-color",
      nameForTitle: "Background Color",
      type: "string",
      description: "Color styles for the element's background",
      value: "",
      options: [...customAndGlobalCssOptions],
    },
    {
      name: "background-image",
      nameForTitle: "Background Image",
      type: "string",
      description: "Specifies the background image",
      value: "",
      options: ["none", ...globalCssOptions], // url(), linear gradient()
    },
    {
      name: "background-origin",
      nameForTitle: "Background Origin",
      type: "string",
      description: "Specifies the origin position of the background image",
      value: "",
      options: ["border-box", "padding-box", "content-box", ...globalCssOptions],
    },
    {
      name: "background-position", // upto 4 vaues
      nameForTitle: "Background Position",
      type: "string",
      description: "Specifies the position of the background image",
      value: "",
      options: [...namedPositions, "percentage", "length", ...globalCssOptions],
    },
    {
      name: "background-position-x",
      nameForTitle: "Background Position X",
      type: "string",
      description: "Specifies the x-coordinate of the background image",
      value: "",
      options: ["left", "center", "right", "percentage", "length", ...globalCssOptions],
    },
    {
      name: "background-position-y",
      nameForTitle: "Background Position Y",
      type: "string",
      description: "Specifies the y-coordinate of the background image",
      value: "",
      options: ["top", "center", "bottom", "percentage", "length", ...globalCssOptions],
    },
    {
      name: "background-repeat",
      nameForTitle: "Background Repeat",
      type: "string",
      description: "Specifies how the background image repeats",
      value: "",
      maxOptionCounts: 2,
      options: [
        "repeat",
        "repeat-x",
        "repeat-y",
        "no-repeat",
        "space",
        "round",
        ...globalCssOptions,
      ],
    },
    {
      name: "background-size",
      nameForTitle: "Background Size",
      type: "string",
      description: "Specifies the size of the background image",
      value: "",
      options: ["auto", "cover", "contain", "percentage", "length", ...globalCssOptions],
    },
  ],
};
const ColorGroup = {
  groupName: "Color Group",
  propertyNames: ["color", "color-scheme"],
  groups: [
    {
      name: "color",
      nameForTitle: "Color",
      type: "string",
      description: "Defines the color of the text for the element.",
      value: "",
      options: [...customAndGlobalCssOptions],
    },
    {
      name: "color-scheme",
      nameForTitle: "Color Scheme",
      type: "string",
      description:
        "Specifies the preferred color scheme for the element, allowing for light and dark modes.",
      value: "",
      options: ["normal", "light", "dark", "light dark", "only light", ...globalCssOptions],
    },
  ],
};
export const STYLE_GROUP: StyleGroup[] = [AlignGroup, BackgroundGroup, ColorGroup];
