import { Style, StyleGroup } from "@/types/styleTypes";
export const globalCssOptions = ["inherit", "initial", "revert", "revert-layer", "unset"];
export const customAndGlobalCssOptions = [
  "custom",
  "inherit",
  "initial",
  "revert",
  "revert-layer",
  "unset",
];
export const namedPositions = ["left", "right", "top", "bottom", "center"];
export const lengthUnits = [
  "px",
  "%",
  "em",
  "rem",
  "cm",
  "mm",
  "in",
  "pt",
  "pc",
  "ch",
  "vw",
  "vh",
  "vmin",
  "vmax",
];
export const LengthUnit: Style = {
  name: "length",
  nameForTitle: "Length",
  type: "string",
  description: "Unit of lengths",
  value: "",
  options: [...lengthUnits],
};

export const GLOBAL_STYLES: Style[] = [
  {
    name: "align-content",
    description:
      "Aligns the flex container's lines within the flex container when there is extra space on the cross-axis",
    value: "",
  },
  {
    name: "background-color",
    description: "Color Styles for the element",
    value: "",
  },
  {
    name: "color",
    description: "Color Styles for the element",
    value: "",
  },
  {
    name: "color-scheme",
    description: "Color Styles for the element",
    value: "",
  },
];
const AlignGroup: StyleGroup = {
  groupName: "Alignment Properties",
  propertyNames: ["align-content", "align-items", "align-self"],
  groups: [
    {
      name: "align-content",
      nameForTitle: "Align Content",
      type: "string",
      description:
        "Aligns the flex container's lines within the flex container when there is extra space on the cross-axis",
      value: "",
      options: [
        "normal",
        "start",
        "center",
        "end",
        "flex-start",
        "flex-end",
        "baseline",
        "first baseline",
        "last baseline",
        "space-between",
        "space-around",
        "space-evenly",
        "stretch",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
    {
      name: "align-items",
      nameForTitle: "Align Items",
      type: "string",
      description:
        "Aligns flex items along the cross-axis of the current line of the flex container",
      value: "",
      options: [
        "normal",
        "stretch",
        "center",
        "start",
        "end",
        "flex-start",
        "flex-end",
        "self-start",
        "self-end",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
    {
      name: "align-self",
      nameForTitle: "Align Self",
      type: "string",
      description:
        "Allows the default alignment (or the one specified by align-items) to be overridden for individual flex items",
      value: "",
      options: [
        "auto",
        "normal",
        "center",
        "start",
        "end",
        "self-start",
        "self-end",
        "flex-start",
        "flex-end",
        "anchor-center",
        "baseline",
        "first baseline",
        "last baseline",
        "stretch",
        "safe center",
        "unsafe center",
        ...globalCssOptions,
      ],
    },
  ],
};
const BackgroundGroup: StyleGroup = {
  groupName: "Background Properties",
  propertyNames: [
    "background",
    "background-color",
    "background-attachment",
    "background-blend-mode",
    "background-clip",
    "background-image",
    "background-origin",
    "background-position",
    "background-position-x",
    "background-position-y",
    "background-repeat",
    "background-size",
  ],
  groups: [
    {
      name: "background",
      nameForTitle: "Background",
      type: "string",
      description: "Shorthand for setting all background properties",
      value: "",
      options: [...customAndGlobalCssOptions],
    },
    {
      name: "background-attachment",
      nameForTitle: "Background Attachment",
      type: "string",
      description:
        "Specifies whether the background image is fixed or scrolls with the rest of the page",
      value: "",
      maxOptionCounts: 2,
      options: ["scroll", "fixed", "local", ...globalCssOptions],
    },
    {
      name: "background-blend-mode",
      nameForTitle: "Background Blend Mode",
      type: "string",
      description: "Specifies the blending mode of the background images",
      value: "",
      maxOptionCounts: 2,
      options: [
        "normal",
        "multiply",
        "screen",
        "overlay",
        "darken",
        "lighten",
        "color-dodge",
        "color-burn",
        "hard-light",
        "soft-light",
        "difference",
        "exclusion",
        "hue",
        "saturation",
        "color",
        "luminosity",
        ...globalCssOptions,
      ],
    },
    {
      name: "background-clip",
      nameForTitle: "Background Clip",
      type: "string",
      description: "Specifies the painting area of the background",
      value: "",
      options: ["border-box", "padding-box", "content-box", "text", ...globalCssOptions],
    },
    {
      name: "background-color",
      nameForTitle: "Background Color",
      type: "string",
      description: "Color styles for the element's background",
      value: "",
      options: [...customAndGlobalCssOptions],
    },
    {
      name: "background-image",
      nameForTitle: "Background Image",
      type: "string",
      description: "Specifies the background image",
      value: "",
      options: ["none", ...globalCssOptions], // url(), linear gradient()
    },
    {
      name: "background-origin",
      nameForTitle: "Background Origin",
      type: "string",
      description: "Specifies the origin position of the background image",
      value: "",
      options: ["border-box", "padding-box", "content-box", ...globalCssOptions],
    },
    {
      name: "background-position", // upto 4 vaues
      nameForTitle: "Background Position",
      type: "string",
      description: "Specifies the position of the background image",
      value: "",
      options: [...namedPositions, "length", ...globalCssOptions],
    },
    {
      name: "background-position-x",
      nameForTitle: "Background Position X",
      type: "string",
      description: "Specifies the x-coordinate of the background image",
      value: "",
      options: ["left", "center", "right", "length", ...globalCssOptions],
    },
    {
      name: "background-position-y",
      nameForTitle: "Background Position Y",
      type: "string",
      description: "Specifies the y-coordinate of the background image",
      value: "",
      options: ["top", "center", "bottom", "length", ...globalCssOptions],
    },
    {
      name: "background-repeat",
      nameForTitle: "Background Repeat",
      type: "string",
      description: "Specifies how the background image repeats",
      value: "",
      maxOptionCounts: 2,
      options: [
        "repeat",
        "repeat-x",
        "repeat-y",
        "no-repeat",
        "space",
        "round",
        ...globalCssOptions,
      ],
    },
    {
      name: "background-size",
      nameForTitle: "Background Size",
      type: "string",
      description: "Specifies the size of the background image",
      value: "",
      options: ["auto", "cover", "contain", "length", ...globalCssOptions],
    },
  ],
};
const ColorGroup: StyleGroup = {
  groupName: "Color Properties",
  propertyNames: ["color", "color-scheme"],
  groups: [
    {
      name: "color",
      nameForTitle: "Color",
      type: "string",
      description: "Defines the color of the text for the element.",
      value: "",
      options: [...customAndGlobalCssOptions],
    },
    {
      name: "color-scheme",
      nameForTitle: "Color Scheme",
      type: "string",
      description:
        "Specifies the preferred color scheme for the element, allowing for light and dark modes.",
      value: "",
      options: ["normal", "light", "dark", "light dark", "only light", ...globalCssOptions],
    },
  ],
};
const FlexGroup: StyleGroup = {
  groupName: "Flex Properties",
  propertyNames: [
    "flex-basis",
    "flex-direction",
    "flex-flow",
    "flex-grow",
    "flex-shrink",
    "flex-wrap",
  ],
  groups: [
    {
      name: "flex-basis",
      nameForTitle: "Flex Basis",
      type: "string",
      description: "Specifies the initial main size of a flex item",
      value: "",
      options: [
        "auto",
        "content",
        "min-content",
        "max-content",
        "fit-content",
        "length",
        ...globalCssOptions,
      ],
    },
    {
      name: "flex-direction",
      nameForTitle: "Flex Direction",
      type: "string",
      description: "Defines the direction of the flex container's main axis",
      value: "",
      options: ["row", "row-reverse", "column", "column-reverse", ...globalCssOptions],
    },
    {
      name: "flex-flow",
      nameForTitle: "Flex Flow",
      type: "string",
      description: "A shorthand property for the flex-direction and flex-wrap properties",
      value: "",
      maxOptionCounts: 2,
      options: [
        "row",
        "row-reverse",
        "column",
        "column-reverse",
        "nowrap",
        "wrap",
        "wrap-reverse",
        ...globalCssOptions,
      ],
    },
    {
      name: "flex-grow",
      nameForTitle: "Flex Grow",
      type: "string",
      description:
        "Specifies how much a flex item will grow relative to the rest of the flex items",
      value: "",
      options: ["number", ...globalCssOptions],
    },
    {
      name: "flex-shrink",
      nameForTitle: "Flex Shrink",
      type: "string",
      description:
        "Specifies how much a flex item will shrink relative to the rest of the flex items",
      value: "",
      options: ["number", ...globalCssOptions],
    },
    {
      name: "flex-wrap",
      nameForTitle: "Flex Wrap",
      type: "string",
      description:
        "Specifies whether flex items are forced into a single line or can be wrapped onto multiple lines",
      value: "",
      options: ["nowrap", "wrap", "wrap-reverse", ...globalCssOptions],
    },
  ],
};
const MarginGroup: StyleGroup = {
  groupName: "Margin Properties",
  propertyNames: [
    "margin-block-end",
    "margin-block-start",
    "margin-bottom",
    "margin-inline-end",
    "margin-inline-start",
    "margin-left",
    "margin-right",
    "margin-top",
  ],
  groups: [
    {
      name: "margin-block-end",
      nameForTitle: "Margin Block End",
      type: "string",
      description: "Defines the logical block-end margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-block-start",
      nameForTitle: "Margin Block Start",
      type: "string",
      description: "Defines the logical block-start margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-bottom",
      nameForTitle: "Margin Bottom",
      type: "string",
      description: "Sets the margin area on the bottom of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-inline-end",
      nameForTitle: "Margin Inline End",
      type: "string",
      description: "Defines the logical inline-end margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-inline-start",
      nameForTitle: "Margin Inline Start",
      type: "string",
      description: "Defines the logical inline-start margin of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-left",
      nameForTitle: "Margin Left",
      type: "string",
      description: "Sets the margin area on the left side of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-right",
      nameForTitle: "Margin Right",
      type: "string",
      description: "Sets the margin area on the right side of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
    {
      name: "margin-top",
      nameForTitle: "Margin Top",
      type: "string",
      description: "Sets the margin area on the top of an element.",
      value: "",
      options: ["auto", "length", ...globalCssOptions],
    },
  ],
};

export const STYLE_GROUP: StyleGroup[] = [
  AlignGroup,
  BackgroundGroup,
  ColorGroup,
  FlexGroup,
  MarginGroup,
];
