import { Style, StyleGroup } from "@/types/styleTypes";
export const globalCssOptions = ["inherit", "initial", "revert", "revert-layer", "unset"];
export const customAndGlobalCssOptions = [
  "custom",
  "inherit",
  "initial",
  "revert",
  "revert-layer",
  "unset",
];
export const namedPositionCombinations = [
  "left",
  "left top",
  "left center",
  "left bottom",
  "right",
  "right top",
  "right center",
  "right bottom",
  "center",
  "center top",
  "center center",
  "center bottom",
  "top",
  "top left",
  "top center",
  "top right",
  "bottom",
  "bottom left",
  "bottom center",
  "bottom right",
];
export const lengthUnits = [
  "px",
  "em",
  "rem",
  "cm",
  "mm",
  "in",
  "pt",
  "pc",
  "ch",
  "vw",
  "vh",
  "vmin",
  "vmax",
];
export const Length: Style = {
  name: "length",
  nameForTitle: "Length",
  type: "string",
  description: "Unit of lengths",
  value: "",
  options: [...lengthUnits],
};

export const GLOBAL_STYLES: Style[] = [
  {
    name: "background-color",
    nameForTitle: "Background Color",
    type: "string",
    description: "Color Styles for the element",
    value: "",
    options: [...customAndGlobalCssOptions],
  },
  {
    name: "color",
    nameForTitle: "Color",
    type: "string",
    description: "Color Styles for the element",
    value: "",
    options: [...customAndGlobalCssOptions],
  },
  {
    name: "color-scheme",
    nameForTitle: "Color Scheme",
    type: "string",
    description: "Color Styles for the element",
    value: "",
    options: ["normal", "light", "dark", "light dark", "only light", ...globalCssOptions],
  },
];
export const STYLE_GROUP: StyleGroup[] = [
  {
    groupName: "Background Group",
    propertyNames: [
      "background",
      "background-color",
      "background-attachment",
      "background-blend-mode",
      "background-clip",
      "background-image",
      "background-origin",
      "background-position",
      "background-position-x",
      "background-position-y",
      "background-repeat",
      "background-size",
    ],
    groups: [
      {
        name: "background",
        nameForTitle: "Background",
        type: "string",
        description: "Shorthand for setting all background properties",
        value: "",
        options: [...customAndGlobalCssOptions],
      },
      {
        name: "background-attachment",
        nameForTitle: "Background Attachment",
        type: "string",
        description:
          "Specifies whether the background image is fixed or scrolls with the rest of the page",
        value: "",
        maxOptionCounts: 2,
        options: ["scroll", "fixed", "local", ...globalCssOptions],
      },
      {
        name: "background-blend-mode",
        nameForTitle: "Background Blend Mode",
        type: "string",
        description: "Specifies the blending mode of the background images",
        value: "",
        maxOptionCounts: 2,
        options: [
          "normal",
          "multiply",
          "screen",
          "overlay",
          "darken",
          "lighten",
          "color-dodge",
          "color-burn",
          "hard-light",
          "soft-light",
          "difference",
          "exclusion",
          "hue",
          "saturation",
          "color",
          "luminosity",
          ...globalCssOptions,
        ],
      },
      {
        name: "background-clip",
        nameForTitle: "Background Clip",
        type: "string",
        description: "Specifies the painting area of the background",
        value: "",
        options: ["border-box", "padding-box", "content-box", "text", ...globalCssOptions],
      },
      {
        name: "background-color",
        nameForTitle: "Background Color",
        type: "string",
        description: "Color styles for the element's background",
        value: "",
        options: [...customAndGlobalCssOptions],
      },
      {
        name: "background-image",
        nameForTitle: "Background Image",
        type: "string",
        description: "Specifies the background image",
        value: "",
        options: ["none", ...globalCssOptions], // url(), linear gradient()
      },
      {
        name: "background-origin",
        nameForTitle: "Background Origin",
        type: "string",
        description: "Specifies the origin position of the background image",
        value: "",
        options: ["border-box", "padding-box", "content-box", ...globalCssOptions],
      },
      {
        name: "background-position", // upto 4 vaues
        nameForTitle: "Background Position",
        type: "string",
        description: "Specifies the position of the background image",
        value: "",
        options: [...namedPositionCombinations, "percentage", "length", ...globalCssOptions],
      },
      {
        name: "background-position-x",
        nameForTitle: "Background Position X",
        type: "string",
        description: "Specifies the x-coordinate of the background image",
        value: "",
        options: ["left", "center", "right", "percentage", "length", ...globalCssOptions],
      },
      {
        name: "background-position-y",
        nameForTitle: "Background Position Y",
        type: "string",
        description: "Specifies the y-coordinate of the background image",
        value: "",
        options: ["top", "center", "bottom", "percentage", "length", ...globalCssOptions],
      },
      {
        name: "background-repeat",
        nameForTitle: "Background Repeat",
        type: "string",
        description: "Specifies how the background image repeats",
        value: "",
        maxOptionCounts: 2,
        options: [
          "repeat",
          "repeat-x",
          "repeat-y",
          "no-repeat",
          "space",
          "round",
          ...globalCssOptions,
        ],
      },
      {
        name: "background-size",
        nameForTitle: "Background Size",
        type: "string",
        description: "Specifies the size of the background image",
        value: "",
        options: ["auto", "cover", "contain", "percentage", "length", ...globalCssOptions],
      },
    ],
  },
  {
    groupName: "Color Group",
    propertyNames: ["color", "color-scheme"],
    groups: [
      {
        name: "color",
        nameForTitle: "Color",
        type: "string",
        description: "Defines the color of the text for the element.",
        value: "",
        options: [...customAndGlobalCssOptions],
      },
      {
        name: "color-scheme",
        nameForTitle: "Color Scheme",
        type: "string",
        description:
          "Specifies the preferred color scheme for the element, allowing for light and dark modes.",
        value: "",
        options: ["normal", "light", "dark", "light dark", "only light", ...globalCssOptions],
      },
    ],
  },
];
