import { Attribute } from "../../types/attributeTypes";

export const ARIA_ROLES: Attribute = {
  name: "role",
  nameForTitle: "Role",
  description: "Specifies the role of the element in accessibility",
  value: "",
  options: [
    "alert",
    "alertdialog",
    "application",
    "article",
    "banner",
    "button",
    "cell",
    "checkbox",
    "columnheader",
    "combobox",
    "complementary",
    "contentinfo",
    "definition",
    "dialog",
    "directory",
    "document",
    "feed",
    "figure",
    "form",
    "grid",
    "gridcell",
    "group",
    "heading",
    "img",
    "link",
    "list",
    "listbox",
    "listitem",
    "log",
    "main",
    "marquee",
    "math",
    "menu",
    "menubar",
    "menuitem",
    "menuitemcheckbox",
    "menuitemradio",
    "navigation",
    "none",
    "note",
    "option",
    "presentation",
    "progressbar",
    "radio",
    "radiogroup",
    "region",
    "row",
    "rowgroup",
    "rowheader",
    "scrollbar",
    "search",
    "searchbox",
    "separator",
    "slider",
    "spinbutton",
    "status",
    "switch",
    "tab",
    "table",
    "tablist",
    "tabpanel",
    "term",
    "textbox",
    "timer",
    "toolbar",
    "tooltip",
    "tree",
    "treegrid",
    "treeitem",
    "doc-abstract",
    "doc-acknowledgments",
    "doc-afterword",
    "doc-appendix",
    "doc-backlink",
    "doc-biblioentry",
    "doc-bibliography",
    "doc-biblioref",
    "doc-chapter",
    "doc-colophon",
    "doc-conclusion",
    "doc-cover",
    "doc-credit",
    "doc-credits",
    "doc-dedication",
    "doc-endnote",
    "doc-endnotes",
    "doc-epigraph",
    "doc-epilogue",
    "doc-errata",
    "doc-example",
    "doc-footnote",
    "doc-foreword",
    "doc-glossary",
    "doc-glossref",
    "doc-index",
    "doc-introduction",
    "doc-noteref",
    "doc-notice",
    "doc-pagebreak",
    "doc-pagelist",
    "doc-part",
    "doc-preface",
    "doc-prologue",
    "doc-pullquote",
    "doc-qna",
    "doc-subtitle",
    "doc-tip",
    "doc-toc",
  ],
};
export const ARIA_ROLES_DESCRIPTION = {
  alert: "A message with important, time-sensitive information.",
  alertdialog: "A type of dialog that contains an alert message.",
  application:
    "A region declared as a web application, rather than a document.",
  article:
    "A section of content that forms an independent part of a document or site.",
  banner: "A region that contains site-oriented content.",
  button: "An input that allows for user-triggered actions.",
  cell: "A cell in a tabular container.",
  checkbox:
    "A checkable input that has three possible values: true, false, or mixed.",
  columnheader: "A cell containing header information for a column.",
  combobox:
    "An input that can be used to select a single item from a list of items.",
  complementary: "A supporting section that relates to the main content.",
  contentinfo:
    "A large perceivable region containing information about the parent document.",
  definition: "A definition of a term or concept.",
  dialog:
    "A dialog is a window that is overlaid on either the primary window or another dialog window.",
  directory: "A list of references to members of a group.",
  document:
    "A region containing related information that is declared as document content.",
  feed: "A scrollable list of articles where articles are added or removed dynamically.",
  figure:
    "A perceivable region that typically contains a graphic, chart, or image.",
  form: "A landmark region that contains a collection of items and objects that, as a whole, combine to create a form.",
  grid: "A grid is an interactive control which contains cells of tabular data.",
  gridcell: "A cell in a grid or treegrid.",
  group:
    "A set of user interface objects which are not intended to be included in a page summary or table of contents by assistive technologies.",
  heading: "A heading for a section of the page.",
  img: "A container for a collection of elements that form an image.",
  link: "An interactive reference to a resource.",
  list: "A group of non-interactive list items.",
  listbox:
    "A widget that allows the user to select one or more items from a list of options.",
  listitem: "A single item in a list or directory.",
  log: "A type of live region where new information is added in a meaningful order and old information may disappear.",
  main: "The main content of a document.",
  marquee:
    "A type of live region where non-essential information changes frequently.",
  math: "A section of content that represents a mathematical expression.",
  menu: "A type of widget that offers a list of choices to the user.",
  menubar:
    "A presentation of menu that usually remains visible and is typically presented horizontally.",
  menuitem: "An option in a set of choices contained by a menu or menubar.",
  menuitemcheckbox:
    "A checkable menuitem in a set of choices contained by a menu or menubar.",
  menuitemradio:
    "A checkable menuitem in a set of choices contained by a menu or menubar.",
  navigation:
    "A collection of navigational elements (usually links) for navigating the document or related documents.",
  none: "A non-interactive element; synonym for presentation.",
  note: "A section whose content is parenthetic or ancillary to the main content of the resource.",
  option: "A selectable item in a listbox.",
  presentation:
    "An element whose implicit native role semantics will not be mapped to the accessibility API.",
  progressbar:
    "An element that displays the progress status for tasks that take a long time.",
  radio: "A radio button.",
  radiogroup: "A group of radio buttons.",
  region: "A large perceivable section of a web page or document.",
  row: "A row of cells in a tabular container.",
  rowgroup: "A group of rows in a grid.",
  rowheader: "A cell containing header information for a row.",
  scrollbar: "A scrollbar.",
  search:
    "A landmark region that contains a collection of items and objects that, as a whole, combine to create a search facility.",
  searchbox: "A type of textbox intended for specifying search criteria.",
  separator:
    "A divider that separates and distinguishes sections of content or groups of menuitems.",
  slider: "An input where the user selects a value from within a given range.",
  spinbutton:
    "A form of range that expects the user to select from among discrete choices.",
  status: "A type of live region whose content is advisory information.",
  switch: "A type of checkbox that represents on/off values.",
  tab: "A grouping label providing a mechanism for selecting the tab content that is to be rendered to the user.",
  table: "A table containing rows and columns of cells.",
  tablist: "A list of tab elements, which are references to tabpanel elements.",
  tabpanel: "A container for the resources associated with a tab.",
  term: "A word or phrase with a corresponding definition.",
  textbox: "An input that allows free-form text as its value.",
  timer:
    "A type of live region containing a numerical counter which indicates an amount of elapsed time from a start point, or the time remaining until an end point.",
  toolbar:
    "A collection of commonly used function buttons or controls represented in compact visual form.",
  tooltip: "A contextual popup that displays a description for an element.",
  tree: "A type of list that may contain sub-level nested groups that can be expanded or collapsed.",
  treegrid:
    "A grid whose rows can be expanded and collapsed in the same manner as a tree.",
  treeitem: "An option in a tree that can be expanded or collapsed.",
  docAbstract: "A brief summary of the content of a document.",
  docAcknowledgments:
    "A section that lists people who contributed to the work.",
  docAfterword: "A concluding section added at the end of a document.",
  docAppendix: "Supplementary material usually added at the end of a document.",
  docBacklink:
    "A link to a corresponding footnote, endnote, or reference point.",
  docBiblioentry: "A single entry in a bibliography.",
  docBibliography:
    "A section that lists books and other works cited or consulted by the author.",
  docBiblioref: "A citation or reference to a bibliographic entry.",
  docChapter: "A main division of a book or document.",
  docColophon:
    "A brief statement containing information about the publication.",
  docConclusion:
    "A summary of the content, findings, or outcomes of a document.",
  docCover: "The cover image of a document.",
  docCredit: "Credit for the content or a part of the content of a document.",
  docCredits: "A list of credits for the content of a document.",
  docDedication: "A section that dedicates the document to someone.",
  docEndnote: "A note placed at the end of a document or section.",
  docEndnotes: "A section that lists the endnotes for a document.",
  docEpigraph: "A quotation set at the beginning of a document or section.",
  docEpilogue:
    "A section at the end of a document that comments on the conclusion or provides additional details.",
  docErrata: "A section that lists corrections to a document.",
  docExample: "An example in a document.",
  docFootnote: "A note at the bottom of a page or section.",
  docForeword:
    "A section that precedes the main text, usually written by someone other than the author.",
  docGlossary: "A list of terms and definitions used in the document.",
  docGlossref: "A reference to a glossary entry.",
  docIndex: "A section that lists terms or topics and associated page numbers.",
  docIntroduction: "A section that introduces the document.",
  docNoteref: "A reference to a footnote or endnote.",
  docNotice: "A section that contains notices or announcements.",
  docPagebreak: "An explicit page break.",
  docPagelist: "A list of pages in a document.",
  docPart: "A major division of a document.",
  docPreface:
    "A section that precedes the main text, usually written by the author.",
  docPrologue: "An introductory section before the main text.",
  docPullquote:
    "A quotation taken from the document and presented in a visually distinct manner.",
  docQna: "A section with questions and answers.",
  docSubtitle: "A secondary, explanatory title.",
  docTip: "A section that provides tips or helpful hints.",
  docToc: "A table of contents.",
};
