export const languageTags = {
  Abkhaz: "ab",
  Afar: "aa",
  Afrikaans: "af",
  "Afrikaans - South Africa": "af-ZA",
  Akan: "ak",
  Albanian: "sq",
  "Albanian - Albania": "sq-AL",
  Amharic: "am",
  Arabic: "ar",
  "Arabic - Algeria": "ar-DZ",
  "Arabic - Bahrain": "ar-BH",
  "Arabic - Egypt": "ar-EG",
  "Arabic - Iraq": "ar-IQ",
  "Arabic - Jordan": "ar-JO",
  "Arabic - Kuwait": "ar-KW",
  "Arabic - Lebanon": "ar-LB",
  "Arabic - Libya": "ar-LY",
  "Arabic - Morocco": "ar-MA",
  "Arabic - Oman": "ar-OM",
  "Arabic - Qatar": "ar-QA",
  "Arabic - Saudi Arabia": "ar-SA",
  "Arabic - Syria": "ar-SY",
  "Arabic - Tunisia": "ar-TN",
  "Arabic - United Arab Emirates": "ar-AE",
  "Arabic - Yemen": "ar-YE",
  Aragonese: "an",
  Armenian: "hy",
  "Armenian - Armenia": "hy-AM",
  Assamese: "as",
  Avaric: "av",
  Avestan: "ae",
  Aymara: "ay",
  Azerbaijani: "az",
  "Azeri (Cyrillic) - Azerbaijan": "Cy-az-AZ",
  "Azeri (Latin) - Azerbaijan": "Lt-az-AZ",
  Bambara: "bm",
  Bashkir: "ba",
  Basque: "eu",
  "Basque - Basque": "eu-ES",
  Belarusian: "be",
  "Belarusian - Belarus": "be-BY",
  Bengali: "bn",
  Berber: "ber",
  Bihari: "bh",
  Bislama: "bi",
  Bosnian: "bs",
  Breton: "br",
  Bulgarian: "bg",
  "Bulgarian - Bulgaria": "bg-BG",
  Burmese: "my",
  Catalan: "ca",
  "Catalan - Catalan": "ca-ES",
  Chamorro: "ch",
  Chechen: "ce",
  Chichewa: "ny",
  Chinese: "zh",
  "Chinese - China": "zh-CN",
  "Chinese - Hong Kong SAR": "zh-HK",
  "Chinese - Macau SAR": "zh-MO",
  "Chinese - Taiwan": "zh-TW",
  "Chinese (Simplified)": "zh-CHS",
  "Chinese (Traditional)": "zh-CHT",
  Chuvash: "cv",
  Cornish: "kw",
  Corsican: "co",
  Cree: "cr",
  Croatian: "hr",
  "Croatian - Croatia": "hr-HR",
  Czech: "cs",
  "Czech - Czech Republic": "cs-CZ",
  Danish: "da",
  "Danish - Denmark": "da-DK",
  Divehi: "dv",
  "Dhivehi - Maldives": "div-MV",
  Dutch: "nl",
  "Dutch - Belgium": "nl-BE",
  "Dutch - The Netherlands": "nl-NL",
  Dzongkha: "dz",
  English: "en",
  "English - Australia": "en-AU",
  "English - Belize": "en-BZ",
  "English - Canada": "en-CA",
  "English - Caribbean": "en-CB",
  "English - Ireland": "en-IE",
  "English - Jamaica": "en-JM",
  "English - New Zealand": "en-NZ",
  "English - Philippines": "en-PH",
  "English - South Africa": "en-ZA",
  "English - Trinidad and Tobago": "en-TT",
  "English - United Kingdom": "en-GB",
  "English - United States": "en-US",
  "English - Zimbabwe": "en-ZW",
  "English - Singapore": "en-SG",
  Esperanto: "eo",
  Estonian: "et",
  "Estonian - Estonia": "et-EE",
  Ewe: "ee",
  Faroese: "fo",
  "Faroese - Faroe Islands": "fo-FO",
  Fijian: "fj",
  Finnish: "fi",
  "Finnish - Finland": "fi-FI",
  French: "fr",
  "French - Belgium": "fr-BE",
  "French - Canada": "fr-CA",
  "French - France": "fr-FR",
  "French - Luxembourg": "fr-LU",
  "French - Monaco": "fr-MC",
  "French - Switzerland": "fr-CH",
  Fula: "ff",
  Galician: "gl",
  "Galician - Galician": "gl-ES",
  Georgian: "ka",
  "Georgian - Georgia": "ka-GE",
  German: "de",
  "German - Austria": "de-AT",
  "German - Germany": "de-DE",
  "German - Liechtenstein": "de-LI",
  "German - Luxembourg": "de-LU",
  "German - Switzerland": "de-CH",
  Greek: "el",
  "Greek - Greece": "el-GR",
  Guaraní: "gn",
  Gujarati: "gu",
  "Gujarati - India": "gu-IN",
  Haitian: "ht",
  Hausa: "ha",
  Hebrew: "he",
  "Hebrew - Israel": "he-IL",
  Herero: "hz",
  Hindi: "hi",
  "Hindi - India": "hi-IN",
  "Hiri Motu": "ho",
  Hungarian: "hu",
  "Hungarian - Hungary": "hu-HU",
  Interlingua: "ia",
  Indonesian: "id",
  "Indonesian - Indonesia": "id-ID",
  Interlingue: "ie",
  Irish: "ga",
  Igbo: "ig",
  Inupiaq: "ik",
  Ido: "io",
  Icelandic: "is",
  "Icelandic - Iceland": "is-IS",
  Italian: "it",
  "Italian - Italy": "it-IT",
  "Italian - Switzerland": "it-CH",
  Inuktitut: "iu",
  Japanese: "ja",
  "Japanese - Japan": "ja-JP",
  Javanese: "jv",
  Kalaallisut: "kl",
  Kannada: "kn",
  "Kannada - India": "kn-IN",
  Kanuri: "kr",
  Kashmiri: "ks",
  Kazakh: "kk",
  "Kazakh - Kazakhstan": "kk-KZ",
  Khmer: "km",
  Kikuyu: "ki",
  Kinyarwanda: "rw",
  Kyrgyz: "ky",
  "Kyrgyz - Kazakhstan": "ky-KZ",
  Komi: "kv",
  Kongo: "kg",
  Korean: "ko",
  "Korean - Korea": "ko-KR",
  Kurdish: "ku",
  Kwanyama: "kj",
  Latin: "la",
  Luxembourgish: "lb",
  Ganda: "lg",
  Limburgish: "li",
  Lingala: "ln",
  Lao: "lo",
  Lithuanian: "lt",
  "Lithuanian - Lithuania": "lt-LT",
  "Luba-Katanga": "lu",
  Latvian: "lv",
  "Latvian - Latvia": "lv-LV",
  Manx: "gv",
  Macedonian: "mk",
  "Macedonian (FYROM)": "mk-MK",
  Malagasy: "mg",
  Malay: "ms",
  "Malay - Brunei": "ms-BN",
  "Malay - Malaysia": "ms-MY",
  Malayalam: "ml",
  Maltese: "mt",
  Māori: "mi",
  "Marathi (MarÄá¹­hÄ«)": "mr",
  "Marathi - India": "mr-IN",
  Marshallese: "mh",
  Mongolian: "mn",
  "Mongolian - Mongolia": "mn-MN",
  Nauru: "na",
  Navajo: "nv",
  "Norwegian BokmÃ¥l": "nb",
  "Norwegian (BokmÃ¥l) - Norway": "nb-NO",
  "Northern Ndebele": "nd",
  "Northern Sotho": "nso",
  Nepali: "ne",
  Ndonga: "ng",
  "Norwegian Nynorsk": "nn",
  "Norwegian (Nynorsk) - Norway": "nn-NO",
  Norwegian: "no",
  Nuosu: "ii",
  "Southern Ndebele": "nr",
  Occitan: "oc",
  Ojibwe: "oj",
  "Old Church Slavonic": "cu",
  Oromo: "om",
  Oriya: "or",
  Ossetian: "os",
  Panjabi: "pa",
  "Punjabi - India": "pa-IN",
  Pāli: "pi",
  Persian: "fa",
  "Farsi - Iran": "fa-IR",
  Polish: "pl",
  "Polish - Poland": "pl-PL",
  Pashto: "ps",
  Portuguese: "pt",
  "Portuguese - Brazil": "pt-BR",
  "Portuguese - Portugal": "pt-PT",
  Quechua: "qu",
  Romansh: "rm",
  Kirundi: "rn",
  Romanian: "ro",
  "Romanian - Romania": "ro-RO",
  Russian: "ru",
  "Russian - Russia": "ru-RU",
  "Sanskrit (Saá¹ská¹›ta)": "sa",
  "Sanskrit - India": "sa-IN",
  Sardinian: "sc",
  Sindhi: "sd",
  "Northern Sami": "se",
  Samoan: "sm",
  Sango: "sg",
  Serbian: "sr",
  "Serbian (Cyrillic) - Serbia": "Cy-sr-SP",
  "Serbian (Latin) - Serbia": "Lt-sr-SP",
  "Scottish Gaelic": "gd",
  Shona: "sn",
  Sinhala: "si",
  Slovak: "sk",
  "Slovak - Slovakia": "sk-SK",
  Slovene: "sl",
  "Slovenian - Slovenia": "sl-SI",
  Somali: "so",
  "Southern Sotho": "st",
  Spanish: "es",
  "Spanish - Argentina": "es-AR",
  "Spanish - Bolivia": "es-BO",
  "Spanish - Chile": "es-CL",
  "Spanish - Colombia": "es-CO",
  "Spanish - Costa Rica": "es-CR",
  "Spanish - Dominican Republic": "es-DO",
  "Spanish - Ecuador": "es-EC",
  "Spanish - El Salvador": "es-SV",
  "Spanish - Guatemala": "es-GT",
  "Spanish - Honduras": "es-HN",
  "Spanish - Mexico": "es-MX",
  "Spanish - Nicaragua": "es-NI",
  "Spanish - Panama": "es-PA",
  "Spanish - Paraguay": "es-PY",
  "Spanish - Peru": "es-PE",
  "Spanish - Puerto Rico": "es-PR",
  "Spanish - Spain": "es-ES",
  "Spanish - Uruguay": "es-UY",
  "Spanish - Venezuela": "es-VE",
  Sundanese: "su",
  Swahili: "sw",
  "Swahili - Kenya": "sw-KE",
  Swati: "ss",
  Swedish: "sv",
  "Swedish - Finland": "sv-FI",
  "Swedish - Sweden": "sv-SE",
  Tamil: "ta",
  "Tamil - India": "ta-IN",
  Telugu: "te",
  "Telugu - India": "te-IN",
  Tajik: "tg",
  Thai: "th",
  "Thai - Thailand": "th-TH",
  Tigrinya: "ti",
  "Tibetan Standard": "bo",
  Turkmen: "tk",
  Tagalog: "tl",
  Filipino: "fil",
  Tswana: "tn",
  "Tonga (Tonga Islands)": "to",
  Turkish: "tr",
  "Turkish - Turkey": "tr-TR",
  Tsonga: "ts",
  Tatar: "tt",
  "Tatar - Russia": "tt-RU",
  Twi: "tw",
  Tahitian: "ty",
  Uyghur: "ug",
  Ukrainian: "uk",
  "Ukrainian - Ukraine": "uk-UA",
  Urdu: "ur",
  "Urdu - Pakistan": "ur-PK",
  Uzbek: "uz",
  "Uzbek (Cyrillic) - Uzbekistan": "Cy-uz-UZ",
  "Uzbek (Latin) - Uzbekistan": "Lt-uz-UZ",
  Venda: "ve",
  Vietnamese: "vi",
  "Vietnamese - Vietnam": "vi-VN",
  Volapük: "vo",
  Walloon: "wa",
  Welsh: "cy",
  Wolof: "wo",
  "Western Frisian": "fy",
  Xhosa: "xh",
  Yiddish: "yi",
  Yoruba: "yo",
  Zhuang: "za",
  Zulu: "zu",
  Achinese: "ace",
  Acoli: "ach",
  Adangme: "ada",
  Adyghe: "ady",
  "Afro-Asiatic languages": "afa",
  Afrihili: "afh",
  Ainu: "ain",
  Akkadian: "akk",
  Aleut: "ale",
  "Algonquian languages": "alg",
  "Southern Altai": "alt",
  "English, Old (ca.450-1100)": "ang",
  Angika: "anp",
  "Apache languages": "apa",
  "Official Aramaic (700-300 BCE)": "arc",
  Mapudungun: "arn",
  Arapaho: "arp",
  "Artificial languages": "art",
  Arawak: "arw",
  Asturian: "ast",
  "Athapascan languages": "ath",
  "Australian languages": "aus",
  Awadhi: "awa",
  "Banda languages": "bad",
  "Bamileke languages": "bai",
  Baluchi: "bal",
  Balinese: "ban",
  Basa: "bas",
  "Baltic languages": "bat",
  Beja: "bej",
  Bemba: "bem",
  Bhojpuri: "bho",
  Bikol: "bik",
  Bini: "bin",
  Siksika: "bla",
  "Bantu languages": "bnt",
  Braj: "bra",
  "Batak languages": "btk",
  Buriat: "bua",
  Buginese: "bug",
  Blin: "byn",
  Caddo: "cad",
  "Central American Indian languages": "cai",
  "Galibi Carib": "car",
  "Caucasian languages": "cau",
  Cebuano: "ceb",
  "Celtic languages": "cel",
  Chibcha: "chb",
  Chagatai: "chg",
  Chuukese: "chk",
  Mari: "chm",
  "Chinook jargon": "chn",
  Choctaw: "cho",
  Chipewyan: "chp",
  Cherokee: "chr",
  Cheyenne: "chy",
  "Chamic languages": "cmc",
  Coptic: "cop",
  "Creoles and pidgins, English based": "cpe",
  "Creoles and pidgins, French-based": "cpf",
  "Creoles and pidgins, Portuguese-based": "cpp",
  "Crimean Tatar": "crh",
  "Creoles and pidgins": "crp",
  Kashubian: "csb",
  "Cushitic languages": "cus",
  Dakota: "dak",
  Dargwa: "dar",
  "Land Dayak languages": "day",
  Delaware: "del",
  "Slave (Athapascan)": "den",
  Dogrib: "dgr",
  Dinka: "din",
  Dogri: "doi",
  "Dravidian languages": "dra",
  "Lower Sorbian": "dsb",
  Duala: "dua",
  "Dutch, Middle (ca.1050-1350)": "dum",
  Dyula: "dyu",
  Efik: "efi",
  "Egyptian (Ancient)": "egy",
  Ekajuk: "eka",
  Elamite: "elx",
  "English, Middle (1100-1500)": "enm",
  Ewondo: "ewo",
  Fang: "fan",
  Fanti: "fat",
  "Finno-Ugrian languages": "fiu",
  Fon: "fon",
  "French, Middle (ca.1400-1600)": "frm",
  "French, Old (842-ca.1400)": "fro",
  "Northern Frisian": "frr",
  "Eastern Frisian": "frs",
  Friulian: "fur",
  Ga: "gaa",
  Gayo: "gay",
  Gbaya: "gba",
  "Germanic languages": "gem",
  Geez: "gez",
  Gilbertese: "gil",
  "German, Middle High (ca.1050-1500)": "gmh",
  "German, Old High (ca.750-1050)": "goh",
  Gondi: "gon",
  Gorontalo: "gor",
  Gothic: "got",
  Grebo: "grb",
  "Greek, Ancient (to 1453)": "grc",
  "Swiss German": "gsw",
  "Gwich'in": "gwi",
  Haida: "hai",
  Hawaiian: "haw",
  Hiligaynon: "hil",
  "Himachali languages": "him",
  Hittite: "hit",
  Hmong: "hmn",
  "Upper Sorbian": "hsb",
  Hupa: "hup",
  Iban: "iba",
  "Ijo languages": "ijo",
  Iloko: "ilo",
  "Indic languages": "inc",
  "Indo-European languages": "ine",
  Ingush: "inh",
  "Iranian languages": "ira",
  "Iroquoian languages": "iro",
  Lojban: "jbo",
  "Judeo-Persian": "jpr",
  "Judeo-Arabic": "jrb",
  "Kara-Kalpak": "kaa",
  Kabyle: "kab",
  Kachin: "kac",
  Kamba: "kam",
  "Karen languages": "kar",
  Kawi: "kaw",
  Kabardian: "kbd",
  Khasi: "kha",
  "Khoisan languages": "khi",
  Khotanese: "kho",
  Kimbundu: "kmb",
  Konkani: "kok",
  "Konkani - India": "kok-IN",
  Kosraean: "kos",
  Kpelle: "kpe",
  "Karachay-Balkar": "krc",
  Karelian: "krl",
  "Kru languages": "kro",
  Kurukh: "kru",
  Kumyk: "kum",
  Kutenai: "kut",
  Ladino: "lad",
  Lahnda: "lah",
  Lamba: "lam",
  Lezghian: "lez",
  Mongo: "lol",
  Lozi: "loz",
  "Luba-Lulua": "lua",
  Luiseno: "lui",
  Lunda: "lun",
  "Luo (Kenya and Tanzania)": "luo",
  Lushai: "lus",
  Madurese: "mad",
  Magahi: "mag",
  Maithili: "mai",
  Makasar: "mak",
  Mandingo: "man",
  "Austronesian languages": "map",
  Masai: "mas",
  Moksha: "mdf",
  Mandar: "mdr",
  Mende: "men",
  "Irish, Middle (900-1200)": "mga",
  "Mi'kmaq": "mic",
  Minangkabau: "min",
  "Uncoded languages": "mis",
  "Mon-Khmer languages": "mkh",
  Manchu: "mnc",
  Manipuri: "mni",
  "Manobo languages": "mno",
  Mohawk: "moh",
  Mossi: "mos",
  "Multiple languages": "mul",
  "Munda languages": "mun",
  Creek: "mus",
  Mirandese: "mwl",
  Marwari: "mwr",
  "Mayan languages": "myn",
  Erzya: "myv",
  "Nahuatl languages": "nah",
  "North American Indian languages": "nai",
  Neapolitan: "nap",
  "Low German": "nds",
  "Nepal Bhasa": "new",
  Nias: "nia",
  "Niger-Kordofanian languages": "nic",
  Niuean: "niu",
  Nogai: "nog",
  "Norse, Old": "non",
  "N'Ko": "nqo",
  "Nubian languages": "nub",
  "Classical Newari": "nwc",
  Nyamwezi: "nym",
  Nyankole: "nyn",
  Nyoro: "nyo",
  Nzima: "nzi",
  Osage: "osa",
  "Turkish, Ottoman (1500-1928)": "ota",
  "Otomian languages": "oto",
  "Papuan languages": "paa",
  Pangasinan: "pag",
  Pahlavi: "pal",
  Pampanga: "pam",
  Papiamento: "pap",
  Palauan: "pau",
  "Persian, Old (ca.600-400 B.C.)": "peo",
  "Philippine languages": "phi",
  Phoenician: "phn",
  Pohnpeian: "pon",
  "Prakrit languages": "pra",
  "ProvenÃ§al, Old (to 1500)": "pro",
  "Reserved for local use": "qaa-qtz",
  Rajasthani: "raj",
  Rapanui: "rap",
  Rarotongan: "rar",
  "Romance languages": "roa",
  Romany: "rom",
  Aromanian: "rup",
  Sandawe: "sad",
  Yakut: "sah",
  "South American Indian languages": "sai",
  "Salishan languages": "sal",
  "Samaritan Aramaic": "sam",
  Sasak: "sas",
  Santali: "sat",
  Sicilian: "scn",
  Scots: "sco",
  Selkup: "sel",
  "Semitic languages": "sem",
  "Irish, Old (to 900)": "sga",
  "Sign Languages": "sgn",
  Shan: "shn",
  Sidamo: "sid",
  "Siouan languages": "sio",
  "Sino-Tibetan languages": "sit",
  "Slavic languages": "sla",
  "Southern Sami": "sma",
  "Sami languages": "smi",
  "Lule Sami": "smj",
  "Inari Sami": "smn",
  "Skolt Sami": "sms",
  Soninke: "snk",
  Sogdian: "sog",
  "Songhai languages": "son",
  "Sranan Tongo": "srn",
  Serer: "srr",
  "Nilo-Saharan languages": "ssa",
  Sukuma: "suk",
  Susu: "sus",
  Sumerian: "sux",
  "Classical Syriac": "syc",
  Syriac: "syr",
  "Syriac - Syria": "syr-SY",
  "Tai languages": "tai",
  Timne: "tem",
  Tereno: "ter",
  Tetum: "tet",
  Tigre: "tig",
  Tiv: "tiv",
  Tokelau: "tkl",
  Klingon: "tlh",
  Tlingit: "tli",
  Tamashek: "tmh",
  "Tonga (Nyasa)": "tog",
  "Tok Pisin": "tpi",
  Tsimshian: "tsi",
  Tumbuka: "tum",
  "Tupi languages": "tup",
  "Altaic languages": "tut",
  Tuvalu: "tvl",
  Tuvinian: "tyv",
  Udmurt: "udm",
  Ugaritic: "uga",
  Umbundu: "umb",
  Undetermined: "und",
  Vai: "vai",
  Votic: "vot",
  "Wakashan languages": "wak",
  Wolaitta: "wal",
  Waray: "war",
  Washo: "was",
  "Sorbian languages": "wen",
  Kalmyk: "xal",
  Yao: "yao",
  Yapese: "yap",
  "Yupik languages": "ypk",
  Zapotec: "zap",
  Blissymbols: "zbl",
  Zenaga: "zen",
  "Standard Moroccan Tamazight": "zgh",
  "Zande languages": "znd",
  Zuni: "zun",
  Zaza: "zza",
};
